import type { FiveSAudit } from "@/features/five-s/types/five-s";
import type { MyAction } from "@/features/five-s/types/my-actions";
import type { ContinuousImprovement } from "@/features/five-s/continuous-improvement/types";
import type { GembaState } from "@/features/gemba/types";
import type { RedFlag } from "@/features/red-flag/types";
import type { VisualImprovement } from "@/features/visual-improvement/types";
import { REPORT_TYPES, getReportModule, type ReportTypeId } from "./report-registry";

export interface ReportSummaryColumn {
  key: string;
  label: string;
}

export interface ReportSummaryEvidencePair {
  id: string;
  reference: string;
  module: string;
  title: string;
  before?: string;
  after?: string;
  description: string;
  owner: string;
  completionDate: string;
}

export interface ReportSummaryModel {
  typeId: ReportTypeId;
  title: string;
  moduleLabel: string;
  description: string;
  reference: string;
  generatedAt: string;
  sourceHref: string;
  columns: ReportSummaryColumn[];
  rows: Array<Record<string, string>>;
  evidencePairs?: ReportSummaryEvidencePair[];
}

export interface ReportSummaryInput {
  audits: FiveSAudit[];
  actions: MyAction[];
  improvements: ContinuousImprovement[];
  redFlags: RedFlag[];
  visualImprovements: VisualImprovement[];
  gemba: GembaState;
  now?: Date;
}

export function buildReportSummary(typeId: ReportTypeId, input: ReportSummaryInput): ReportSummaryModel | null {
  const generatedAt = (input.now ?? new Date()).toISOString();
  if (typeId === "nonComplianceSummary") return nonCompliance(input, generatedAt);
  if (typeId === "beforeAfterSummary") return beforeAfter(input, generatedAt);
  if (typeId === "overdueActionSummary") return overdueActions(input, generatedAt);
  if (typeId === "benefitSavingsSummary") return ciSavings(input, generatedAt);
  if (typeId === "visualSavingsSummary") return visualSavings(input, generatedAt);
  if (typeId === "gembaObservationSummary") return gembaObservations(input, generatedAt);
  if (typeId === "gembaActionSummary") return gembaActions(input, generatedAt);
  return null;
}

export function reportSummaryToCsv(report: ReportSummaryModel) {
  const header = report.columns.map((column) => column.label);
  const rows = report.rows.map((row) => report.columns.map((column) => row[column.key] ?? ""));
  return [header, ...rows].map((row) => row.map(csvCell).join(",")).join("\r\n");
}

export function reportLibraryToCsv(rows: Array<Record<string, string>>) {
  const columns = ["Report", "Module", "Reference", "Plant", "Zone", "Generated By", "Date", "Status"];
  return [columns, ...rows.map((row) => columns.map((column) => row[column] ?? ""))]
    .map((row) => row.map(csvCell).join(","))
    .join("\r\n");
}

function nonCompliance(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const actionMap = new Map(input.actions.map((action) => [action.id, action]));
  const rows = input.audits.flatMap((audit) => audit.sections.flatMap((section) => section.questions
    .filter((question) => question.status === "Fail" || question.score === 0 || question.actionRequired)
    .map((question) => {
      const linked = question.actionId ? actionMap.get(question.actionId) : input.actions.find((action) => action.auditId === audit.id && action.questionId === question.id);
      return {
        audit: audit.id,
        question: question.question,
        category: section.category,
        zone: audit.area,
        observation: question.observation ?? question.description ?? "No observation recorded",
        severity: linked?.priority ?? "Not classified",
        action: linked?.id ?? question.actionId ?? "No action",
        status: linked?.status ?? (question.actionRequired ? "Action required" : "Open"),
      };
    })));
  return summary("nonComplianceSummary", "Failed and action-required audit checks with their linked corrective work.", "/audits", generatedAt, [
    column("audit", "Audit"), column("question", "Question"), column("category", "5S Stage / Category"), column("zone", "Zone"),
    column("observation", "Observation"), column("severity", "Severity"), column("action", "Action"), column("status", "Status"),
  ], rows);
}

function beforeAfter(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const actionPairs: ReportSummaryEvidencePair[] = input.actions.filter((action) => action.status === "Completed").map((action) => ({
    id: `action:${action.id}`, reference: action.id, module: "Actions", title: action.title,
    before: firstImage(action.issueEvidence), after: firstImage(action.evidence),
    description: action.resolutionObservation ?? action.actionTakenDescription ?? action.description,
    owner: action.completedByName ?? action.responsiblePersonName ?? action.assignedTo,
    completionDate: action.completedAt ?? "",
  }));
  const ciPairs: ReportSummaryEvidencePair[] = input.improvements.filter((item) => item.status === "completed").map((item) => ({
    id: `ci:${item.id}`, reference: item.id, module: "Continuous Improvement", title: item.title,
    before: item.beforeEvidence[0]?.url ?? item.existingPhotos[0]?.url,
    after: item.afterEvidence[0]?.url ?? item.evidence[0]?.url,
    description: item.actualBenefit ?? item.actionTaken ?? item.proposedImprovement,
    owner: item.completedByName ?? item.ownerName, completionDate: item.completedAt ?? "",
  }));
  const evidencePairs = [...actionPairs, ...ciPairs];
  const rows = evidencePairs.map((pair) => ({
    module: pair.module, reference: pair.reference, title: pair.title, before: pair.before ?? "No image",
    after: pair.after ?? "No image", description: pair.description, owner: pair.owner, completionDate: pair.completionDate,
  }));
  return {
    ...summary("beforeAfterSummary", "Paired evidence from completed Actions and Continuous Improvements.", "/actions?tab=completed", generatedAt, [
      column("module", "Module"), column("reference", "Reference"), column("title", "Report"), column("before", "Before"),
      column("after", "After"), column("description", "Description"), column("owner", "Owner"), column("completionDate", "Completion Date"),
    ], rows),
    evidencePairs,
  };
}

function overdueActions(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const now = new Date(generatedAt);
  const rows = input.actions.filter((action) => action.status !== "Completed" && new Date(`${action.dueDate}T23:59:59`).getTime() < now.getTime()).map((action) => ({
    action: action.id, title: action.title, source: action.sourceLabel ?? action.sourceTitle, plant: action.plant, zone: action.area,
    priority: action.priority, owner: action.responsiblePersonName ?? action.assignedTo, dueDate: action.dueDate, status: action.status,
  }));
  return summary("overdueActionSummary", "Open Actions that have passed their due date.", "/actions?status=Overdue", generatedAt, [
    column("action", "Action"), column("title", "Title"), column("source", "Source"), column("plant", "Plant"),
    column("zone", "Zone"), column("priority", "Priority"), column("owner", "Owner"), column("dueDate", "Due Date"), column("status", "Status"),
  ], rows);
}

function ciSavings(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const rows = input.improvements.map((item) => ({
    improvement: item.id, title: item.title, plant: item.plant, zone: item.zone, benefitType: item.benefitType,
    proposedBenefit: item.expectedBenefit, proposedSaving: money(item.proposedSaving), actualBenefit: item.actualBenefit ?? "Not recorded",
    actualSaving: item.actualSaving === undefined ? "Not recorded" : money(item.actualSaving), variance: item.actualSaving === undefined ? "—" : money(item.actualSaving - item.proposedSaving), status: humanStatus(item.status),
  }));
  return summary("benefitSavingsSummary", "Proposed and realized Continuous Improvement benefits and savings.", "/continuous-improvement", generatedAt, [
    column("improvement", "Improvement"), column("title", "Title"), column("plant", "Plant"), column("zone", "Zone"),
    column("benefitType", "Benefit Type"), column("proposedBenefit", "Proposed Benefit"), column("proposedSaving", "Proposed Saving"),
    column("actualBenefit", "Actual Benefit"), column("actualSaving", "Actual Saving"), column("variance", "Variance"), column("status", "Status"),
  ], rows);
}

function visualSavings(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const rows = input.visualImprovements.map((item) => ({
    improvement: item.id, title: item.title, category: item.category, plant: item.plant, zone: item.zone, owner: item.ownerName,
    proposedSaving: item.proposedCostSaving === undefined ? "Not recorded" : money(item.proposedCostSaving),
    actualSaving: item.actualCostSaving === undefined ? "Not recorded" : money(item.actualCostSaving),
    benefit: item.benefitDescription ?? item.expectedBenefit, status: item.status,
  }));
  return summary("visualSavingsSummary", "Financial and non-financial benefits recorded by Visual Improvements.", "/visual-improvement", generatedAt, [
    column("improvement", "Improvement"), column("title", "Title"), column("category", "Category"), column("plant", "Plant"),
    column("zone", "Zone"), column("owner", "Owner"), column("proposedSaving", "Proposed Saving"), column("actualSaving", "Actual Saving"), column("benefit", "Benefit"), column("status", "Status"),
  ], rows);
}

function gembaObservations(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const walks = new Map(input.gemba.walks.map((walk) => [walk.id, walk]));
  const rows = input.gemba.observations.map((observation) => {
    const walk = walks.get(observation.gembaId);
    return { walk: observation.gembaId, observation: observation.id, type: observation.type, title: observation.title,
      plant: walk?.plant ?? "—", zone: walk?.zone ?? "—", location: observation.location, raisedBy: observation.createdByName,
      action: observation.actionId ?? observation.noActionReason ?? "No action", date: observation.createdAt };
  });
  return summary("gembaObservationSummary", "Positive, opportunity, and issue observations captured during Gemba walks.", "/gemba?tab=observations", generatedAt, [
    column("walk", "Gemba Walk"), column("observation", "Observation"), column("type", "Type"), column("title", "Title"),
    column("plant", "Plant"), column("zone", "Zone"), column("location", "Location"), column("raisedBy", "Captured By"), column("action", "Follow-up"), column("date", "Date"),
  ], rows);
}

function gembaActions(input: ReportSummaryInput, generatedAt: string): ReportSummaryModel {
  const actionMap = new Map(input.actions.map((action) => [action.id, action]));
  const walkMap = new Map(input.gemba.walks.map((walk) => [walk.id, walk]));
  const rows = input.gemba.observations.filter((observation) => observation.actionId).map((observation) => {
    const action = actionMap.get(observation.actionId!);
    const walk = walkMap.get(observation.gembaId);
    return { walk: observation.gembaId, observation: observation.id, finding: observation.title, action: observation.actionId!,
      actionTitle: action?.title ?? "Linked action", owner: action?.responsiblePersonName ?? action?.assignedTo ?? "Not assigned",
      zone: walk?.zone ?? "—", dueDate: action?.dueDate ?? "—", status: action?.status ?? "Not found" };
  });
  return summary("gembaActionSummary", "Actions created from Gemba observations with current ownership and status.", "/gemba?tab=observations", generatedAt, [
    column("walk", "Gemba Walk"), column("observation", "Observation"), column("finding", "Finding"), column("action", "Action"),
    column("actionTitle", "Action Title"), column("owner", "Owner"), column("zone", "Zone"), column("dueDate", "Due Date"), column("status", "Status"),
  ], rows);
}

function summary(typeId: ReportTypeId, description: string, sourceHref: string, generatedAt: string, columns: ReportSummaryColumn[], rows: Array<Record<string, string>>): ReportSummaryModel {
  const definition = REPORT_TYPES[typeId];
  return {
    typeId, title: definition.label, moduleLabel: getReportModule(definition.module).label, description, sourceHref,
    generatedAt, reference: `OPS-${typeId.replace(/[a-z]/g, "").slice(0, 8)}-${generatedAt.slice(0, 10).replaceAll("-", "")}`,
    columns, rows,
  };
}

function column(key: string, label: string) { return { key, label }; }
function firstImage(evidence: MyAction["evidence"] | undefined) { return evidence?.find((item) => item.type === "image" && item.url)?.url; }
function money(value: number) { return `INR ${value.toLocaleString("en-IN")}`; }
function humanStatus(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function csvCell(value: string) { const text = String(value ?? ""); return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
