import { describe,expect,it,vi } from "vitest";
import { DEMO_USERS } from "@/lib/current-user";
import { ROLE_PRESETS,hasPermission,permissionsForRoles } from "@/features/five-s/administration/permissions";
import type { AdminUserInput } from "@/features/five-s/administration/types";

function storage(){const values=new Map<string,string>();return{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key)}}
async function adminStore(localStorage=storage()){vi.resetModules();vi.stubGlobal("window",{localStorage});vi.stubGlobal("localStorage",localStorage);vi.stubGlobal("crypto",{randomUUID:()=>"new-user"});return import("@/features/five-s/administration/store")}
const input:AdminUserInput={employeeId:"EMP-NEW",name:"New Member",email:"new.member@example.com",plant:"Egmore Plant",status:"Active",roles:["Zone Member"],zoneMemberships:[{zone:"Zone B",responsibility:"Member"}],permissions:permissionsForRoles(["Zone Member"])};

describe("Administration users and permissions",()=>{
  it("shows Administration access only to the seeded Admin",async()=>{const store=await adminStore();const admin=store.getAdminUser(DEMO_USERS.auditor.id),member=store.getAdminUser(DEMO_USERS.responsible.id);expect(hasPermission(admin,"administration.view")).toBe(true);expect(hasPermission(member,"administration.view")).toBe(false);expect(admin?.roles).toEqual(expect.arrayContaining(["Admin","Auditor","Zone Leader"]));});
  it("initializes expected role presets and supports multiple roles",()=>{expect(ROLE_PRESETS.Auditor).toEqual(expect.arrayContaining(["audits.execute","actions.review","reports.export"]));expect(permissionsForRoles(["Zone Member","Auditor"])).toEqual(expect.arrayContaining(["ci.create","actions.work","audits.complete","actions.close"]));});
  it("exposes the fixed Reviewer preset without replacing the legacy Viewer type",()=>{expect(ROLE_PRESETS.Reviewer).toEqual(expect.arrayContaining(["ci.review","actions.review","actions.close"]));expect(permissionsForRoles(["Reviewer"])).not.toContain("administration.manage_users");});
  it("creates, updates and persists customized access after reload",async()=>{const localStorage=storage();const store=await adminStore(localStorage);const created=store.createAdminUser(input,DEMO_USERS.auditor.id)!;expect(created.roles).toEqual(["Zone Member"]);const updated=store.updateAdminUser(created.id,{...input,roles:["Zone Member","Auditor"],permissions:[...permissionsForRoles(["Zone Member","Auditor"]),"administration.view"]},DEMO_USERS.auditor.id)!;expect(updated.roles).toEqual(["Zone Member","Auditor"]);expect(updated.permissions).toContain("administration.view");const reloaded=await adminStore(localStorage);expect(reloaded.getAdminUser(created.id)?.permissions).toContain("administration.view");});
  it("activates and deactivates users but protects the active Admin",async()=>{const store=await adminStore();const created=store.createAdminUser(input,DEMO_USERS.auditor.id)!;expect(store.setAdminUserActive(created.id,false,DEMO_USERS.auditor.id)).toBe(true);expect(store.getAdminUser(created.id)?.status).toBe("Inactive");expect(store.setAdminUserActive(created.id,true,DEMO_USERS.auditor.id)).toBe(true);expect(()=>store.setAdminUserActive(DEMO_USERS.auditor.id,false,DEMO_USERS.auditor.id)).toThrow("cannot deactivate");expect(()=>store.updateAdminUser(DEMO_USERS.auditor.id,{...input,employeeId:"EMP-LAKSHMAN",roles:["Viewer"],permissions:permissionsForRoles(["Viewer"])},DEMO_USERS.auditor.id)).toThrow("cannot remove your own");});
  it("keeps all existing demo personas represented without conflicting IDs",async()=>{const store=await adminStore();for(const persona of Object.values(DEMO_USERS))expect(store.getAdminUser(persona.id)?.name).toBe(persona.name);});
});
