import { beforeEach, describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import type { FiveSAudit, FiveSSection } from "@/features/five-s/types/five-s";
import {
  createFiveSAudit,
  getFiveSAudits,
  setFiveSAudits,
  startScheduledFiveSAudit,
  updateFiveSAudit,
  updateScheduledFiveSAuditSetup,
  validateFiveSAuditSchedule,
} from "@/lib/five-s/audit-store";

const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");

const sections: FiveSSection[] = [{
  category: "Sort",
  description: "Sort section",
  score: 0,
  maxScore: 2,
  questions: [{
    id: "Q-1",
    category: "Sort",
    question: "Is the area sorted?",
    maxScore: 2,
    score: null,
    status: "Not Started",
    observation: "",
    evidence: [],
    actionRequired: false,
  }],
}];

function createScheduled() {
  return createFiveSAudit({
    title: "Generated by store",
    plant: "Test Plant",
    department: "Production",
    area: "Zone B",
    auditor: "Test Auditor",
    dueDate: "2099-02-01",
    scheduledDate: "2099-01-15",
    scheduledTime: "09:30",
    sections,
  }, { startNow: false });
}

describe("Team Feedback #3/#4 — Audit scheduling lifecycle", () => {
  beforeEach(() => setFiveSAudits([]));

  it("keeps Start Now on the canonical active Audit path", () => {
    const audit = createFiveSAudit({ title: "Generated", plant: "Test Plant", department: "Production", area: "Zone B", auditor: "Test Auditor", dueDate: "2099-02-01", sections });
    expect(audit.status).toBe("In Progress");
    expect(audit.startedAt).toBeTruthy();
  });

  it("requires both schedule fields and rejects past timing", () => {
    const now = new Date("2026-09-24T10:00:00");
    expect(validateFiveSAuditSchedule("", "", now)).toMatch(/date and time/i);
    expect(validateFiveSAuditSchedule("2026-09-24", "09:59", now)).toMatch(/future/i);
    expect(validateFiveSAuditSchedule("2026-09-24", "10:01", now)).toBeNull();
    expect(validateFiveSAuditSchedule("2026-09-25", "08:00", now)).toBeNull();
  });

  it("persists a Scheduled Audit without starting execution", () => {
    const audit = createScheduled();
    expect(audit).toMatchObject({ status: "Scheduled", scheduledDate: "2099-01-15", scheduledTime: "09:30", completionPercentage: 0 });
    expect(audit.startedAt).toBeUndefined();
    expect(getFiveSAudits().find((item) => item.id === audit.id)?.status).toBe("Scheduled");
  });

  it("edits only safe pre-start timing metadata", () => {
    const audit = createScheduled();
    const updated = updateScheduledFiveSAuditSetup(audit.id, { scheduledDate: "2099-01-16", scheduledTime: "11:00", dueDate: "2099-02-02" }, new Date("2026-09-24T10:00:00"));
    expect(updated).toMatchObject({ id: audit.id, title: audit.title, area: "Zone B", scheduledDate: "2099-01-16", scheduledTime: "11:00", dueDate: "2099-02-02" });
  });

  it("starts the same Scheduled record without duplication or execution-data loss", () => {
    const audit = createScheduled();
    const started = startScheduledFiveSAudit(audit.id, new Date("2099-01-15T09:20:00"));
    expect(started).toMatchObject({ id: audit.id, title: audit.title, status: "In Progress" });
    expect(started?.sections).toEqual(audit.sections);
    expect(getFiveSAudits()).toHaveLength(1);
  });

  it("keeps In Progress structural setup immutable while preserving answers and links", () => {
    const audit = createFiveSAudit({ title: "Generated", plant: "Test Plant", department: "Production", area: "Zone B", auditor: "Test Auditor", dueDate: "2099-02-01", sections });
    const answeredSections: FiveSSection[] = [{ ...sections[0], questions: [{ ...sections[0].questions[0], score: 1, status: "Fail", observation: "Finding retained", actionRequired: true, actionId: "ACT-1" }] }];
    const updated = updateFiveSAudit(audit.id, { plant: "Other Plant", area: "Zone C", auditor: "Other Auditor", sections: answeredSections, completionPercentage: 100 });
    expect(updated).toMatchObject({ plant: "Test Plant", area: "Zone B", auditor: "Test Auditor", completionPercentage: 100 });
    expect(updated?.sections[0].questions[0]).toMatchObject({ observation: "Finding retained", actionId: "ACT-1" });
  });

  it("does not start or edit Completed Audits", () => {
    const completed: FiveSAudit = { ...createScheduled(), status: "Completed", completedAt: "2099-01-20", completionPercentage: 100 };
    setFiveSAudits([completed]);
    expect(startScheduledFiveSAudit(completed.id)).toBeUndefined();
    expect(updateScheduledFiveSAuditSetup(completed.id, { scheduledDate: "2099-01-21", scheduledTime: "10:00", dueDate: "2099-02-01" })).toBeUndefined();
    expect(getFiveSAudits()[0]).toEqual(completed);
  });

  it("routes Scheduled records to a pre-start view and keeps Gemba scheduling untouched", () => {
    const auditPage = source("features/five-s/audit-list-page.tsx");
    const scheduledPage = source("features/five-s/components/FiveSAuditScheduled.tsx");
    const gembaPage = source("features/gemba/gemba-new-page.tsx");
    expect(auditPage).toContain('selectedAudit.status === "Scheduled"');
    expect(scheduledPage).toContain("Start Audit");
    expect(scheduledPage).toContain("Save Setup");
    expect(gembaPage).toContain('setMode("schedule")');
    expect(gembaPage).toContain('router.push(startNow ? `/gemba/${walk.id}/walk` : `/gemba/${walk.id}`)');
  });
});
