import { beforeEach, describe, expect, it, vi } from "vitest";
import { evaluateKpiPerformance, validatePerformanceThreshold, type SmartAnalysis, type VisualManagementKpiDefinition } from "@/features/visual-management/kpi-configuration";
import { setVisualManagementKpisForTests } from "@/features/visual-management/kpi-configuration-store";
import { assignKpiToBoard, createMeetingKpiReviewSnapshots, getKpiExecution, linkDeviationAction, submitKpiActual, unassignKpiFromBoard, setKpiExecutionForTests } from "@/features/visual-management/kpi-execution-store";
import { createReportingPeriod, normalizedReportingPeriodKey, readableReportingPeriod, suggestReportingPeriod } from "@/features/visual-management/reporting-period";

describe("Visual Management reporting periods", () => {
  it.each([
    ["2026-09", "2026-09", "September 2026"],
    ["2026-10", "2026-10", "October 2026"],
    ["2026-11", "2026-11", "November 2026"],
  ])("creates a canonical monthly period from %s", (input, key, label) => {
    expect(createReportingPeriod("monthly", input)).toEqual({ type: "monthly", key, label });
  });

  it("reads and compares legacy slash-form monthly keys without rewriting stored data", () => {
    const legacy = { type: "monthly" as const, key: "2026/09", label: "Sep 2026" };
    expect(readableReportingPeriod(legacy)).toBe("September 2026");
    expect(normalizedReportingPeriodKey(legacy)).toBe("2026-09");
  });

  it("suggests October after September", () => {
    expect(suggestReportingPeriod("monthly", { type: "monthly", key: "2026/09", label: "Sep" })).toEqual({ type: "monthly", key: "2026-10", label: "October 2026" });
  });
});

const smart: SmartAnalysis = { specific: { status: "complete", explanation: "Clear" }, measurable: { status: "complete", explanation: "Measured" }, achievable: { status: "complete", explanation: "Possible" }, relevant: { status: "complete", explanation: "Relevant" }, timely: { status: "complete", explanation: "Dated" } };
function definition(patch: Partial<VisualManagementKpiDefinition> = {}): VisualManagementKpiDefinition { return { id: "VMK-U-1", level: "unit", name: "First Pass Yield", originalObjective: "Improve yield", smartObjective: "Improve yield to 98%", smartAnalysis: smart, bucket: "quality", indicatorType: "lagging", measurementType: "percentage", direction: "higher_is_better", baseline: 94.5, target: 98, targetDate: "2027-03-31", performanceThreshold: { direction: "higher_is_better", amberBoundary: 95 }, status: "active", createdAt: "2026-09-29T00:00:00Z", updatedAt: "2026-09-29T00:00:00Z", ...patch }; }

beforeEach(() => { vi.stubGlobal("window", undefined); vi.stubGlobal("crypto", { randomUUID: vi.fn().mockReturnValueOnce("a1").mockReturnValueOnce("a2").mockReturnValueOnce("a3").mockReturnValue("a4") }); setVisualManagementKpisForTests([definition()]); setKpiExecutionForTests({ assignments: [], actualEntries: [], deviations: [] }); });

describe("Visual Management KPI performance thresholds", () => {
  it("evaluates higher-is-better using only the explicit boundary", () => { const t = { direction: "higher_is_better", amberBoundary: 95 } as const; expect(evaluateKpiPerformance(98, "percentage", "higher_is_better", 98, t)).toBe("green"); expect(evaluateKpiPerformance(99, "percentage", "higher_is_better", 98, t)).toBe("green"); expect(evaluateKpiPerformance(96, "percentage", "higher_is_better", 98, t)).toBe("amber"); expect(evaluateKpiPerformance(94, "percentage", "higher_is_better", 98, t)).toBe("red"); });
  it("evaluates lower-is-better using only the explicit boundary", () => { const t = { direction: "lower_is_better", amberBoundary: 3 } as const; expect(evaluateKpiPerformance(2, "number", "lower_is_better", 2, t)).toBe("green"); expect(evaluateKpiPerformance(1, "number", "lower_is_better", 2, t)).toBe("green"); expect(evaluateKpiPerformance(2.5, "number", "lower_is_better", 2, t)).toBe("amber"); expect(evaluateKpiPerformance(4, "number", "lower_is_better", 2, t)).toBe("red"); });
  it("requires explicit two-sided exact-target bounds and never invents tolerance", () => { const t = { direction: "target_exactly", amberLowerBound: 9, amberUpperBound: 11 } as const; expect(evaluateKpiPerformance(10, "number", "target_exactly", 10, t)).toBe("green"); expect(evaluateKpiPerformance(9.5, "number", "target_exactly", 10, t)).toBe("amber"); expect(evaluateKpiPerformance(12, "number", "target_exactly", 10, t)).toBe("red"); expect(evaluateKpiPerformance(10.1, "number", "target_exactly", 10)).toBe("unavailable"); });
  it("rejects impossible and missing thresholds", () => { expect(validatePerformanceThreshold("higher_is_better", 98, { direction: "higher_is_better", amberBoundary: 99 })).toContain("below"); expect(validatePerformanceThreshold("lower_is_better", 2, { direction: "lower_is_better", amberBoundary: 1 })).toContain("above"); expect(evaluateKpiPerformance(98, "percentage", "higher_is_better", 98)).toBe("unavailable"); });
});

describe("Visual Management KPI execution lifecycle", () => {
  it("stores ID-only assignments, prevents same-board duplicates, and permits another board", () => { const first = assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); expect(first.success).toBe(true); expect(first.success && first.assignment).toEqual(expect.objectContaining({ boardId: "BOARD-1", kpiId: "VMK-U-1" })); expect(first.success && Object.keys(first.assignment)).not.toContain("name"); expect(assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1").success).toBe(false); expect(assignKpiToBoard("BOARD-2", "VMK-U-1", "USR-1").success).toBe(true); });
  it("blocks archived assignment and preserves history on unassignment", () => { setVisualManagementKpisForTests([definition({ status: "archived" })]); expect(assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1").success).toBe(false); setVisualManagementKpisForTests([definition()]); assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); const result = submitKpiActual({ boardId: "BOARD-1", kpiId: "VMK-U-1", value: 99, reportingPeriod: { type: "monthly", key: "2026-09", label: "Sep 2026" }, reportedByUserId: "USR-1" }); expect(result.success).toBe(true); expect(unassignKpiFromBoard("BOARD-1", "VMK-U-1")).toBe(true); expect(getKpiExecution().actualEntries).toHaveLength(1); });
  it("creates immutable Green actual snapshots without a deviation and blocks duplicate period", () => { assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); const input = { boardId: "BOARD-1", kpiId: "VMK-U-1", value: 98.5, reportingPeriod: { type: "monthly" as const, key: "2026-09", label: "Sep 2026" }, reportedByUserId: "USR-1", comment: "On plan" }; const result = submitKpiActual(input); expect(result.success).toBe(true); if (!result.success) return; expect(result.entry).toMatchObject({ boardId: "BOARD-1", kpiId: "VMK-U-1", value: 98.5, reportedByUserId: "USR-1", targetSnapshot: 98, thresholdSnapshot: { amberBoundary: 95 }, measurementSnapshot: "percentage", directionSnapshot: "higher_is_better", statusSnapshot: "green", comment: "On plan" }); expect(result.deviation).toBeUndefined(); expect(submitKpiActual(input)).toMatchObject({ success: false, error: expect.stringContaining("already") }); expect(submitKpiActual({ ...input, reportingPeriod: { type: "monthly", key: "2026-10", label: "Oct 2026" } }).success).toBe(true); });
  it("blocks a canonical monthly duplicate when the stored record uses a legacy slash key", () => { assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); expect(submitKpiActual({ boardId: "BOARD-1", kpiId: "VMK-U-1", value: 98.5, reportingPeriod: { type: "monthly", key: "2026/09", label: "Sep 2026" }, reportedByUserId: "USR-1" }).success).toBe(true); expect(submitKpiActual({ boardId: "BOARD-1", kpiId: "VMK-U-1", value: 99, reportingPeriod: { type: "monthly", key: "2026-09", label: "September 2026" }, reportedByUserId: "USR-1" })).toMatchObject({ success: false, error: expect.stringContaining("September 2026") }); });
  it("requires deviation decisions for Amber/Red and a justification when no Action is needed", () => { assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); const base = { boardId: "BOARD-1", kpiId: "VMK-U-1", value: 96, reportingPeriod: { type: "weekly" as const, key: "2026-W40", label: "Week 40" }, reportedByUserId: "USR-1" }; expect(submitKpiActual(base).success).toBe(false); expect(submitKpiActual({ ...base, deviationComment: "Minor process drift", correctiveActionRequired: false }).success).toBe(false); const amber = submitKpiActual({ ...base, deviationComment: "Minor process drift", correctiveActionRequired: false, noActionJustification: "Contained during shift" }); expect(amber.success).toBe(true); if (amber.success) expect(amber.deviation).toMatchObject({ kpiActualEntryId: amber.entry.id, status: "amber", correctiveActionRequired: false, noActionJustification: "Contained during shift" }); });
  it("supports Action retry without duplicating the actual/deviation or Action link", () => { assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); const red = submitKpiActual({ boardId: "BOARD-1", kpiId: "VMK-U-1", value: 92, reportingPeriod: { type: "weekly", key: "2026-W41", label: "Week 41" }, reportedByUserId: "USR-1", deviationComment: "Yield loss", correctiveActionRequired: true }); expect(red.success).toBe(true); if (!red.success || !red.deviation) return; expect(getKpiExecution().actualEntries).toHaveLength(1); expect(linkDeviationAction(red.deviation.id, "ACT-1")).toBe(true); expect(linkDeviationAction(red.deviation.id, "ACT-2")).toBe(false); expect(getKpiExecution().deviations[0].actionId).toBe("ACT-1"); });
  it("keeps historical status and meeting snapshots unchanged after KPI edits", () => { assignKpiToBoard("BOARD-1", "VMK-U-1", "USR-1"); const actual = submitKpiActual({ boardId: "BOARD-1", kpiId: "VMK-U-1", value: 96, reportingPeriod: { type: "monthly", key: "2026-09", label: "Sep" }, reportedByUserId: "USR-1", deviationComment: "Drift", correctiveActionRequired: false, noActionJustification: "Monitoring" }); expect(actual.success).toBe(true); const reviews = createMeetingKpiReviewSnapshots("MEETING-1", "BOARD-1", "USR-1"); expect(reviews[0]).toMatchObject({ kpiActualEntryId: actual.success ? actual.entry.id : "", kpiNameSnapshot: "First Pass Yield", actualSnapshot: 96, targetSnapshot: 98, statusSnapshot: "amber", deviationSnapshot: "Drift" }); setVisualManagementKpisForTests([definition({ name: "Renamed", target: 99, direction: "lower_is_better", performanceThreshold: { direction: "lower_is_better", amberBoundary: 100 } })]); expect(getKpiExecution().actualEntries[0]).toMatchObject({ targetSnapshot: 98, directionSnapshot: "higher_is_better", statusSnapshot: "amber" }); expect(reviews[0]).toMatchObject({ kpiNameSnapshot: "First Pass Yield", targetSnapshot: 98, statusSnapshot: "amber" }); });
});
