"use client";

import { useMemo, useState } from "react";
import { Archive, ArrowLeft, BrainCircuit, Check, ChevronRight, Edit3, Plus, Target } from "lucide-react";
import { PageContainer } from "@/components/layout/page-container";
import { OpsFeedback } from "@/components/ops/ops-feedback";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { FieldMessage } from "@/components/ui/field-message";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAdminUsers } from "@/features/five-s/administration/store";
import FiveSPageHeader from "@/features/five-s/components/FiveSPageHeader";
import { formatKpiNumericValue, formatKpiTarget, getKpiThresholdPresentation, KPI_BUCKETS, KPI_BUCKET_LABELS, KPI_DIRECTIONS, KPI_DIRECTION_LABELS, KPI_FUNCTIONS, KPI_INDICATOR_TYPES, KPI_INDICATOR_TYPE_LABELS, KPI_MEASUREMENT_LABELS, KPI_MEASUREMENT_TYPES, KPI_REVIEW_FREQUENCIES, KPI_REVIEW_FREQUENCY_LABELS, resolveKpiOwnerName, SMART_DIMENSIONS, validateKpiDefinition, type KpiAnalysisResult, type KpiDriverSuggestion, type KpiFactKey, type KpiFactSource, type VisualManagementKpiDefinition } from "@/features/visual-management/kpi-configuration";
import { archiveVisualManagementKpi, saveVisualManagementKpi, useVisualManagementKpis } from "@/features/visual-management/kpi-configuration-store";
import { VisualManagementNav } from "@/features/visual-management/visual-management-components";
import { useModuleEntitlements } from "@/lib/module-entitlements";
import { useOrganizationConfiguration } from "@/lib/organization-store";
import { SettingsAccessDenied, useSettingsAccess } from "./settings-access";

type Draft = Omit<VisualManagementKpiDefinition, "id" | "createdAt" | "updatedAt" | "smartAnalysis"> & { id?: string; smartAnalysis?: KpiAnalysisResult["smart"] };
type Feedback = { tone: "success" | "error"; message: string };
const emptySmart = Object.fromEntries(SMART_DIMENSIONS.map((key) => [key, { status: "needs_context", explanation: "Awaiting analysis" }])) as KpiAnalysisResult["smart"];

function fresh(level: "unit" | "functional", parentKpiId?: string): Draft {
  return { level, name: "", originalObjective: "", smartObjective: "", bucket: "quality", indicatorType: level === "unit" ? "lagging" : "leading", measurementType: "number", direction: "lower_is_better", baseline: Number.NaN, target: Number.NaN, targetDate: "", parentKpiId, functionName: level === "functional" ? "" : undefined, ownerUserId: level === "functional" ? "" : undefined, reviewFrequency: level === "functional" ? "daily" : undefined, status: "active" };
}
function date(value: string) { return value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "—"; }
const targetText = formatKpiTarget;

export function VisualManagementKpiConfigurationPage() {
  const access = useSettingsAccess(); const modules = useModuleEntitlements(); const allowed = access.canManageConfiguration && (modules.visualManagement || access.isSuperAdmin);
  const kpis = useVisualManagementKpis(); const users = useAdminUsers(); const organization = useOrganizationConfiguration();
  const [tab, setTab] = useState<"unit" | "functional">("unit"); const [draft, setDraft] = useState<Draft | null>(null); const [view, setView] = useState<VisualManagementKpiDefinition | null>(null); const [feedback, setFeedback] = useState<Feedback>();
  const units = kpis.filter((item) => item.level === "unit" && item.status === "active"); const functional = kpis.filter((item) => item.level === "functional" && item.status === "active");
  const functions = useMemo(() => Array.from(new Set([...organization.zones.map((zone) => zone.department).filter(Boolean), ...KPI_FUNCTIONS])), [organization.zones]);
  function startFunctional(parentId?: string) { if (!units.length) { setTab("unit"); setFeedback({ tone: "error", message: "Configure at least one Unit KPI before creating Functional KPIs." }); return; } setDraft(fresh("functional", parentId)); }
  function edit(item: VisualManagementKpiDefinition) { setDraft({ ...item, smartAnalysis: item.smartAnalysis }); setView(null); }
  function archive(item: VisualManagementKpiDefinition) { const result = archiveVisualManagementKpi(item.id); setFeedback(result.success ? { tone: "success", message: `${item.name} archived.` } : { tone: "error", message: result.error }); setView(null); }
  return <PageContainer><FiveSPageHeader eyebrow="OPS Workspace" title="Visual Management" description="Run daily operational meetings, review performance, track issues, and turn discussions into action." /><VisualManagementNav />{!allowed ? <SettingsAccessDenied area="Visual Management KPI configuration" /> : <>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">KPI Configuration</h2><p className="mt-1 text-sm text-muted-foreground">Define Unit objectives and the Functional KPIs that contribute to them.</p></div><Button onClick={() => tab === "unit" ? setDraft(fresh("unit")) : startFunctional()}><Plus className="size-4" />Add {tab === "unit" ? "Unit" : "Functional"} KPI</Button></div>
    {feedback && <OpsFeedback {...feedback} />}
    <div className="flex border-b" role="tablist" aria-label="KPI levels"><button className={`min-h-11 border-b-2 px-4 text-sm font-medium ${tab === "unit" ? "border-primary text-foreground" : "border-transparent text-muted-foreground"}`} role="tab" aria-selected={tab === "unit"} onClick={() => setTab("unit")}>Unit KPIs <Badge variant="muted">{units.length}</Badge></button><button className={`min-h-11 border-b-2 px-4 text-sm font-medium ${tab === "functional" ? "border-primary text-foreground" : "border-transparent text-muted-foreground"}`} role="tab" aria-selected={tab === "functional"} onClick={() => setTab("functional")}>Functional KPIs <Badge variant="muted">{functional.length}</Badge></button></div>
    {tab === "unit" ? <UnitList items={units} functionalKpis={functional} users={users} onView={setView} onEdit={edit} onAddChild={startFunctional} onAdd={() => setDraft(fresh("unit"))} /> : <FunctionalList items={functional} units={units} users={users} onView={setView} onEdit={edit} onAdd={() => { if (units.length) startFunctional(); else { setTab("unit"); setDraft(fresh("unit")); } }} />}
    {draft && <KpiWizard key={draft.id ?? `${draft.level}-new`} initial={draft} units={units} users={users} functions={functions} onClose={() => setDraft(null)} onSaved={(record) => { setDraft(null); setTab(record.level); setFeedback({ tone: "success", message: `${record.name} ${record.id === draft.id ? "updated" : "created"}.` }); }} />}
    {view && <KpiDetail item={view} parent={kpis.find((item) => item.id === view.parentKpiId)} descendantKpis={functional.filter((item) => item.parentKpiId === view.id)} owner={resolveKpiOwnerName(view.ownerUserId, users)} onClose={() => setView(null)} onEdit={() => edit(view)} onArchive={() => archive(view)} onAddChild={() => { setView(null); startFunctional(view.id); }} />}
  </>}</PageContainer>;
}

function UnitList({ items, functionalKpis, users, onView, onEdit, onAddChild, onAdd }: { items: VisualManagementKpiDefinition[]; functionalKpis: VisualManagementKpiDefinition[]; users: ReturnType<typeof useAdminUsers>; onView: (item: VisualManagementKpiDefinition) => void; onEdit: (item: VisualManagementKpiDefinition) => void; onAddChild: (id: string) => void; onAdd: () => void }) {
  if (!items.length) return <Empty title="Define the objectives your unit needs to achieve." description="OPS AI will help turn each objective into a measurable KPI." action="Add Unit KPI" onAction={onAdd} />;
  return <div className="grid gap-3">{items.map((item) => { const linked = functionalKpis.filter((child) => child.parentKpiId === item.id); return <Card key={item.id} className="gap-0"><CardContent className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.name}</h3><Badge variant="outline">{KPI_BUCKET_LABELS[item.bucket]}</Badge><Badge variant="muted">{KPI_INDICATOR_TYPE_LABELS[item.indicatorType]}</Badge></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><Meta label="Target" value={targetText(item)} /><Meta label="Target Date" value={date(item.targetDate)} /><Meta label="Contributors" value={`${linked.length} Functional KPI${linked.length === 1 ? "" : "s"}`} /></div></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" onClick={() => onView(item)}>View</Button><Button size="sm" variant="ghost" onClick={() => onEdit(item)}><Edit3 className="size-3.5" />Edit</Button><Button size="sm" variant="outline" onClick={() => onAddChild(item.id)}><Plus className="size-3.5" />Add Functional KPI</Button></div></div>{linked.length > 0 && <div className="mt-5 border-l-2 border-primary/20 pl-4">{linked.map((child) => { const owner = users.find((user) => user.id === child.ownerUserId); return <button key={child.id} onClick={() => onView(child)} className="flex min-h-12 w-full items-center gap-3 border-b py-2 text-left last:border-0"><span className="min-w-0 flex-1"><span className="block text-xs text-muted-foreground">{child.functionName} Function · {KPI_BUCKET_LABELS[child.bucket]}</span><span className="block truncate text-sm font-medium">{child.name}</span><span className="mt-0.5 block text-xs text-muted-foreground">{KPI_INDICATOR_TYPE_LABELS[child.indicatorType]} · Owner: {owner?.name ?? "Inactive or unavailable user"} · {child.reviewFrequency ? KPI_REVIEW_FREQUENCY_LABELS[child.reviewFrequency] : "Review frequency unavailable"}</span></span><span className="text-xs text-muted-foreground">Target {targetText(child)}</span><ChevronRight className="size-4" /></button>; })}</div>}</CardContent></Card>; })}</div>;
}
function FunctionalList({ items, units, users, onView, onEdit, onAdd }: { items: VisualManagementKpiDefinition[]; units: VisualManagementKpiDefinition[]; users: ReturnType<typeof useAdminUsers>; onView: (item: VisualManagementKpiDefinition) => void; onEdit: (item: VisualManagementKpiDefinition) => void; onAdd: () => void }) {
  if (!units.length) return <Empty title="Configure at least one Unit KPI before creating Functional KPIs." description="Functional KPIs must contribute to a Unit KPI; orphan KPIs are not allowed." action="Configure Unit KPI" onAction={onAdd} />;
  if (!items.length) return <Empty title="Connect functions to Unit objectives." description="Create measurable drivers with a named owner and review frequency." action="Add Functional KPI" onAction={onAdd} />;
  return <div className="grid gap-3">{items.map((item) => <Card key={item.id} className="gap-0"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">{item.functionName} Function · contributes to {units.find((unit) => unit.id === item.parentKpiId)?.name ?? "Unavailable Unit KPI"}</p><h3 className="mt-1 font-semibold">{item.name}</h3><p className="mt-2 text-sm text-muted-foreground">{KPI_BUCKET_LABELS[item.bucket]} · {KPI_INDICATOR_TYPE_LABELS[item.indicatorType]} · Target {targetText(item)} · Owner: {users.find((user) => user.id === item.ownerUserId)?.name ?? "Inactive or unavailable user"} · {item.reviewFrequency ? KPI_REVIEW_FREQUENCY_LABELS[item.reviewFrequency] : "Review frequency unavailable"}</p></div><div className="flex gap-2"><Button size="sm" variant="ghost" onClick={() => onView(item)}>View</Button><Button size="sm" variant="ghost" onClick={() => onEdit(item)}><Edit3 className="size-3.5" />Edit</Button></div></CardContent></Card>)}</div>;
}
function Empty({ title: heading, description, action, onAction }: { title: string; description: string; action: string; onAction: () => void }) { return <div className="grid min-h-72 place-items-center rounded-xl border border-dashed p-8 text-center"><div><Target className="mx-auto size-8 text-muted-foreground" /><h3 className="mt-4 font-semibold">{heading}</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">{description}</p><Button className="mt-5" onClick={onAction}><Plus className="size-4" />{action}</Button></div></div>; }

function KpiWizard({ initial, units, users, functions, onClose, onSaved }: { initial: Draft; units: VisualManagementKpiDefinition[]; users: ReturnType<typeof useAdminUsers>; functions: string[]; onClose: () => void; onSaved: (item: VisualManagementKpiDefinition) => void }) {
  const editing = Boolean(initial.id); const [draft, setDraft] = useState(initial); const [step, setStep] = useState(editing ? 2 : 0); const [analysis, setAnalysis] = useState<KpiAnalysisResult | null>(null); const [answers, setAnswers] = useState<Partial<Record<KpiFactKey, string>>>({}); const [factSources, setFactSources] = useState<Partial<Record<KpiFactKey, KpiFactSource>>>({}); const [drivers, setDrivers] = useState<KpiDriverSuggestion[]>([]); const [selectedDriver, setSelectedDriver] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  const parent = units.find((item) => item.id === draft.parentKpiId);
  async function request(body: Record<string, unknown>) { const response = await fetch("/api/visual-management/kpi/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : "AI analysis is temporarily unavailable."); return data; }
  async function analyze() { setLoading(true); setError(""); try { const result = await request({ mode: "analyze", objective: draft.originalObjective, context: { answers, level: draft.level, parent: parent ? { name: parent.name, objective: parent.smartObjective, bucket: parent.bucket } : undefined, functionName: draft.functionName, driver: draft.name } }) as KpiAnalysisResult; setAnalysis(result); const sources = { ...factSources }; for (const key of ["baseline", "target", "targetDate", "measurementContext"] as KpiFactKey[]) if (answers[key]) sources[key] = "follow_up"; else if (result.extractedFacts[key] !== null) sources[key] = "objective"; setFactSources(sources); setDraft((current) => ({ ...current, name: result.suggestedKpiName, smartObjective: result.draftSmartObjective, smartAnalysis: result.smart, bucket: result.suggestedBucket, indicatorType: result.suggestedIndicatorType, measurementType: result.suggestedMeasurementType, direction: result.suggestedDirection, baseline: typeof result.extractedFacts.baseline === "number" ? result.extractedFacts.baseline : current.baseline, target: typeof result.extractedFacts.target === "number" ? result.extractedFacts.target : current.target, targetDate: result.extractedFacts.targetDate ?? current.targetDate, reviewFrequency: current.level === "functional" ? result.suggestedReviewFrequency ?? current.reviewFrequency : undefined, relationshipExplanation: result.relationshipExplanation })); setStep(1); } catch (reason) { setError(reason instanceof Error ? reason.message : "AI analysis is temporarily unavailable."); } finally { setLoading(false); } }
  async function suggestDrivers() { if (!parent || !draft.functionName) return setError("Select a Unit KPI and function first."); setLoading(true); setError(""); try { const result = await request({ mode: "drivers", context: { parentName: parent.name, parentObjective: parent.smartObjective, parentBucket: parent.bucket, parentTarget: parent.target, functionName: draft.functionName } }) as { suggestions: KpiDriverSuggestion[] }; setDrivers(result.suggestions); } catch (reason) { setError(reason instanceof Error ? reason.message : "AI analysis is temporarily unavailable."); } finally { setLoading(false); } }
  function preview() { const candidate = { ...draft, id: draft.id ?? "preview", smartAnalysis: draft.smartAnalysis ?? analysis?.smart ?? emptySmart, createdAt: "", updatedAt: "" } as VisualManagementKpiDefinition; const errors = validateKpiDefinition(candidate, units); setFieldErrors(errors); if (!Object.keys(errors).length) setStep(3); }
  function save() { const result = saveVisualManagementKpi({ ...draft, smartAnalysis: draft.smartAnalysis ?? analysis?.smart ?? emptySmart } as Parameters<typeof saveVisualManagementKpi>[0]); if (!result.success) { setFieldErrors(result.errors); setStep(2); return; } onSaved(result.record); }
  const heading = editing ? `Edit ${initial.name}` : `Add ${draft.level === "unit" ? "Unit" : "Functional"} KPI`;
  return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="grid max-h-[calc(100dvh-1rem)] w-[calc(100vw-1rem)] max-w-none grid-rows-[auto_minmax(0,1fr)_auto] overflow-hidden p-0 sm:max-w-4xl xl:max-w-5xl"><DialogHeader className="px-6 pt-6 pr-12"><DialogTitle>{heading}</DialogTitle><DialogDescription>{step === 0 ? draft.level === "unit" ? "Tell OPS what you want to achieve. OPS builds the KPI with you." : "Choose a Unit KPI and function, then let OPS suggest a contributing driver." : step === 1 ? analysis?.complete ? "Review the KPI generated from your objective and confirm its business controls." : "Almost ready — I need a few details to make this KPI measurable." : step === 2 ? "Edit the full KPI configuration." : "Review the KPI before creating it."}</DialogDescription></DialogHeader><div className="min-w-0 overflow-y-auto px-6 py-4">
    {step === 0 && <div className="grid gap-5">{draft.level === "functional" && <><Field label="Which Unit KPI should this function contribute to?"><Select value={draft.parentKpiId || null} onValueChange={(value) => { setSelectedDriver(""); setDrivers([]); setDraft({ ...draft, parentKpiId: value ?? "", name: "", originalObjective: "" }); }}><SelectTrigger><SelectValue placeholder="Select Unit KPI">{parent ? `${parent.name} · ${KPI_BUCKET_LABELS[parent.bucket]} · Unit KPI` : undefined}</SelectValue></SelectTrigger><SelectContent>{units.map((item) => <SelectItem key={item.id} value={item.id}>{item.name} · {KPI_BUCKET_LABELS[item.bucket]} · Unit KPI</SelectItem>)}</SelectContent></Select></Field><Field label="Which function will influence this KPI?"><Select value={draft.functionName || null} onValueChange={(value) => { setSelectedDriver(""); setDrivers([]); setDraft({ ...draft, functionName: value ?? "", name: "", originalObjective: "" }); }}><SelectTrigger><SelectValue placeholder="Select function">{draft.functionName || undefined}</SelectValue></SelectTrigger><SelectContent>{functions.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field><div><Button variant="outline" onClick={suggestDrivers} disabled={loading || !draft.parentKpiId || !draft.functionName}><BrainCircuit className="size-4" />{loading ? "Finding drivers…" : "Suggest KPI drivers"}</Button>{drivers.length > 0 && <div className="mt-3 grid gap-2 sm:grid-cols-2">{drivers.map((item) => <button type="button" key={item.name} onClick={() => { setSelectedDriver(item.name); setDraft({ ...draft, name: item.name, originalObjective: `Improve ${item.name} to contribute to ${parent?.name ?? "the Unit KPI"}.` }); }} className={`rounded-lg border p-3 text-left ${selectedDriver === item.name ? "border-primary bg-primary/[0.04]" : ""}`}><span className="text-sm font-semibold">{item.name}</span><span className="mt-1 block text-xs text-muted-foreground">{item.description}</span></button>)}</div>}<Field label="Or define my own"><Input value={selectedDriver ? "" : draft.name} onChange={(event) => { setSelectedDriver(""); setDraft({ ...draft, name: event.target.value }); }} placeholder="Functional KPI name" /></Field></div></>}
      <Field label={draft.level === "unit" ? "Describe your objective" : "What should this Functional KPI achieve?"}><Textarea autoFocus={draft.level === "unit"} className="min-h-32" value={draft.originalObjective} onChange={(event) => setDraft({ ...draft, originalObjective: event.target.value })} placeholder={draft.level === "unit" ? "Reduce customer complaints from 4.2 complaints per 1,000 units to 2.0 or fewer by March 2027." : "Describe the result this Functional KPI should achieve."} />{draft.level === "unit" && <span className="text-xs font-normal text-muted-foreground">Tell us what you want to improve. Include current performance, desired target and deadline if you know them.</span>}</Field>{error && <div><FieldMessage error>{error}</FieldMessage><Button className="mt-3" variant="outline" onClick={() => { setDraft({ ...draft, smartObjective: draft.originalObjective }); setStep(2); }}>Continue manually</Button></div>}</div>}
    {step === 1 && <div className="grid min-w-0 gap-5">{analysis?.questions.length ? <section><h3 className="font-semibold">Almost ready</h3><p className="mt-1 text-sm text-muted-foreground">I need a few details to make this KPI measurable.</p><div className="mt-4 grid gap-4 md:grid-cols-2">{analysis.questions.map((question) => <Field key={question.id} label={question.label}><Input type={question.inputType} step={question.inputType === "number" ? "any" : undefined} value={answers[question.factKey] ?? ""} onChange={(event) => setAnswers({ ...answers, [question.factKey]: event.target.value })} />{(question.helperText || question.unitHint) && <span className="text-xs font-normal text-muted-foreground">{question.helperText}{question.unitHint ? ` · ${question.unitHint}` : ""}</span>}</Field>)}</div><Button className="mt-4" variant="outline" onClick={analyze} disabled={loading || analysis.questions.some((question) => question.required && !answers[question.factKey]?.trim())}>{loading ? "Generating…" : "Generate KPI"}</Button></section> : <><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-primary">Generated KPI</p><p className="mt-1 text-sm text-muted-foreground">Generated from your objective</p></div><Button variant="outline" onClick={() => setStep(2)}><Edit3 className="size-4" />Edit details</Button></div><Preview draft={draft} parent={parent} owner={draft.ownerUserId ? resolveKpiOwnerName(draft.ownerUserId, users) : undefined} compact /><ThresholdFields draft={draft} setDraft={setDraft} error={fieldErrors.performanceThreshold} />{draft.level === "functional" && <div className="grid gap-4 sm:grid-cols-2"><Field label="Who owns this KPI?" error={fieldErrors.ownerUserId}><Select value={draft.ownerUserId || null} onValueChange={(value) => setDraft({ ...draft, ownerUserId: value ?? "" })}><SelectTrigger><SelectValue placeholder="Select owner">{draft.ownerUserId ? resolveKpiOwnerName(draft.ownerUserId, users) : undefined}</SelectValue></SelectTrigger><SelectContent>{users.filter((item) => item.status === "Active").map((item) => <SelectItem value={item.id} key={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Review frequency"><Select value={draft.reviewFrequency ?? "weekly"} onValueChange={(value) => setDraft({ ...draft, reviewFrequency: (value ?? "weekly") as Draft["reviewFrequency"] })}><SelectTrigger><SelectValue>{KPI_REVIEW_FREQUENCY_LABELS[draft.reviewFrequency ?? "weekly"]}</SelectValue></SelectTrigger><SelectContent>{KPI_REVIEW_FREQUENCIES.map((item) => <SelectItem value={item} key={item}>{KPI_REVIEW_FREQUENCY_LABELS[item]}</SelectItem>)}</SelectContent></Select><span className="text-xs font-normal text-muted-foreground">AI suggestion — confirm or change</span></Field></div>}</>}{error && <OpsFeedback tone="error" message={error} />}</div>}
    {step === 2 && <KpiForm draft={draft} setDraft={setDraft} units={units} users={users} functions={functions} errors={fieldErrors} />}
    {step === 3 && <Preview draft={draft} parent={parent} owner={draft.ownerUserId ? resolveKpiOwnerName(draft.ownerUserId, users) : undefined} />}
    </div><DialogFooter className="gap-2 border-t px-6 py-4 sm:flex-wrap">{step > 0 && <Button variant="outline" onClick={() => setStep(step === 3 ? 1 : step - 1)}><ArrowLeft className="size-4" />Back & Edit</Button>}<Button variant="ghost" onClick={onClose}>Cancel</Button>{step === 0 && <Button onClick={analyze} disabled={loading || !draft.originalObjective.trim() || (draft.level === "functional" && (!draft.parentKpiId || !draft.functionName || !draft.name.trim()))}><BrainCircuit className="size-4" />{loading ? "Generating…" : "Generate KPI"}</Button>}{step === 1 && analysis?.complete && <Button onClick={preview}>Review KPI</Button>}{step === 2 && <Button onClick={preview}>Review KPI</Button>}{step === 3 && <Button onClick={save}><Check className="size-4" />{editing ? "Save Changes" : draft.level === "unit" ? "Create KPI" : "Create Functional KPI"}</Button>}</DialogFooter>
  </DialogContent></Dialog>;
}

function KpiForm({ draft, setDraft, units, users, functions, errors }: { draft: Draft; setDraft: (draft: Draft) => void; units: VisualManagementKpiDefinition[]; users: ReturnType<typeof useAdminUsers>; functions: string[]; errors: Record<string, string> }) { return <div className="grid gap-4 sm:grid-cols-2">{draft.level === "functional" && <><Field label="Parent Unit KPI" error={errors.parentKpiId}><Input value={units.find((item) => item.id === draft.parentKpiId)?.name ?? ""} disabled /></Field><Field label="Function" error={errors.functionName}><Select disabled={Boolean(draft.id)} value={draft.functionName ?? ""} onValueChange={(value) => setDraft({ ...draft, functionName: value ?? "" })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{functions.map((item) => <SelectItem value={item} key={item}>{item}</SelectItem>)}</SelectContent></Select></Field></>}
  <Field label="KPI Name" error={errors.name}><Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Bucket" error={errors.bucket}><Select value={draft.bucket} onValueChange={(value) => setDraft({ ...draft, bucket: (value ?? "quality") as Draft["bucket"] })}><SelectTrigger><SelectValue>{KPI_BUCKET_LABELS[draft.bucket]}</SelectValue></SelectTrigger><SelectContent>{KPI_BUCKETS.map((item) => <SelectItem key={item} value={item}>{KPI_BUCKET_LABELS[item]}</SelectItem>)}</SelectContent></Select></Field>
  <div className="sm:col-span-2"><Field label="SMART Objective" error={errors.smartObjective}><Textarea className="min-h-24" value={draft.smartObjective} onChange={(event) => setDraft({ ...draft, smartObjective: event.target.value })} /></Field></div><Field label="Indicator Type" error={errors.indicatorType}><Select value={draft.indicatorType} onValueChange={(value) => setDraft({ ...draft, indicatorType: (value ?? "lagging") as Draft["indicatorType"] })}><SelectTrigger><SelectValue>{KPI_INDICATOR_TYPE_LABELS[draft.indicatorType]}</SelectValue></SelectTrigger><SelectContent>{KPI_INDICATOR_TYPES.map((item) => <SelectItem key={item} value={item}>{KPI_INDICATOR_TYPE_LABELS[item]}</SelectItem>)}</SelectContent></Select><p className="mt-1 text-xs text-muted-foreground">Leading predicts performance; lagging confirms an outcome.</p></Field><Field label="Measurement" error={errors.measurementType ?? errors.measurement}><Select value={draft.measurementType} onValueChange={(value) => setDraft({ ...draft, measurementType: (value ?? "number") as Draft["measurementType"] })}><SelectTrigger><SelectValue>{KPI_MEASUREMENT_LABELS[draft.measurementType]}</SelectValue></SelectTrigger><SelectContent>{KPI_MEASUREMENT_TYPES.map((item) => <SelectItem key={item} value={item}>{KPI_MEASUREMENT_LABELS[item]}</SelectItem>)}</SelectContent></Select></Field><Field label="Direction" error={errors.direction}><Select value={draft.direction} onValueChange={(value) => setDraft({ ...draft, direction: (value ?? "target_exactly") as Draft["direction"] })}><SelectTrigger><SelectValue>{KPI_DIRECTION_LABELS[draft.direction]}</SelectValue></SelectTrigger><SelectContent>{KPI_DIRECTIONS.map((item) => <SelectItem key={item} value={item}>{KPI_DIRECTION_LABELS[item]}</SelectItem>)}</SelectContent></Select></Field>
  <Field label="Baseline" error={errors.baseline}><Input type="number" step="any" min={draft.measurementType === "percentage" ? 0 : undefined} max={draft.measurementType === "percentage" ? 100 : undefined} value={Number.isFinite(draft.baseline) ? draft.baseline : ""} onChange={(event) => setDraft({ ...draft, baseline: event.target.value === "" ? Number.NaN : Number(event.target.value) })} /></Field><Field label="Target" error={errors.target ?? errors.measurement}><Input type="number" step="any" min={draft.measurementType === "percentage" ? 0 : undefined} max={draft.measurementType === "percentage" ? 100 : undefined} value={Number.isFinite(draft.target) ? draft.target : ""} onChange={(event) => setDraft({ ...draft, target: event.target.value === "" ? Number.NaN : Number(event.target.value) })} /></Field><Field label="Target Date" error={errors.targetDate}><Input type="date" value={draft.targetDate} onChange={(event) => setDraft({ ...draft, targetDate: event.target.value })} /></Field>
  <div className="sm:col-span-2"><ThresholdFields draft={draft} setDraft={setDraft} error={errors.performanceThreshold} /></div>
  {draft.level === "functional" && <><Field label="KPI Owner" error={errors.ownerUserId}><Select value={draft.ownerUserId || null} onValueChange={(value) => setDraft({ ...draft, ownerUserId: value ?? "" })}><SelectTrigger><SelectValue placeholder="Select owner">{draft.ownerUserId ? resolveKpiOwnerName(draft.ownerUserId, users) : undefined}</SelectValue></SelectTrigger><SelectContent>{users.filter((item) => item.status === "Active" || item.id === draft.ownerUserId).map((item) => <SelectItem value={item.id} key={item.id}>{item.name}{item.status === "Inactive" ? " · Inactive" : ""}</SelectItem>)}</SelectContent></Select></Field><Field label="Review Frequency" error={errors.reviewFrequency}><Select value={draft.reviewFrequency ?? "daily"} onValueChange={(value) => setDraft({ ...draft, reviewFrequency: (value ?? "daily") as Draft["reviewFrequency"] })}><SelectTrigger><SelectValue>{KPI_REVIEW_FREQUENCY_LABELS[draft.reviewFrequency ?? "daily"]}</SelectValue></SelectTrigger><SelectContent>{KPI_REVIEW_FREQUENCIES.map((item) => <SelectItem value={item} key={item}>{KPI_REVIEW_FREQUENCY_LABELS[item]}</SelectItem>)}</SelectContent></Select></Field></>}
  </div>; }

function ThresholdFields({ draft, setDraft, error, readOnly = false }: { draft: Draft; setDraft: (draft: Draft) => void; error?: string; readOnly?: boolean }) {
  const unit = draft.measurementType === "percentage" ? "%" : "";
  const boundary = draft.performanceThreshold && "amberBoundary" in draft.performanceThreshold ? draft.performanceThreshold.amberBoundary : Number.NaN;
  const lower = draft.performanceThreshold && "amberLowerBound" in draft.performanceThreshold ? draft.performanceThreshold.amberLowerBound : Number.NaN;
  const upper = draft.performanceThreshold && "amberUpperBound" in draft.performanceThreshold ? draft.performanceThreshold.amberUpperBound : Number.NaN;
  const presentation = getKpiThresholdPresentation(draft as VisualManagementKpiDefinition);
  const targetReady = Number.isFinite(draft.target);
  return <section className="rounded-xl border p-4"><h3 className="text-sm font-semibold">Performance Thresholds</h3><p className="mt-1 text-xs text-muted-foreground">OPS derives Green from the target. You confirm when performance becomes Red.</p>{!readOnly && <div className="mt-4 grid gap-4 sm:grid-cols-3"><Meta label="Target" value={formatKpiNumericValue(draft.target, draft.measurementType)} /><Meta label="Green condition" value={!targetReady ? "Not provided" : draft.direction === "higher_is_better" ? `≥ ${draft.target}${unit}` : draft.direction === "lower_is_better" ? `≤ ${draft.target}${unit}` : `= ${draft.target}${unit}`} />{draft.direction !== "target_exactly" ? <Field label={draft.direction === "lower_is_better" ? "When should this KPI become Red? Above" : "When should this KPI become Red? Below"} error={error}><Input type="number" step="any" value={Number.isFinite(boundary) ? boundary : ""} onChange={(event) => setDraft({ ...draft, performanceThreshold: { direction: draft.direction as "higher_is_better" | "lower_is_better", amberBoundary: event.target.value === "" ? Number.NaN : Number(event.target.value) } })} /></Field> : <><Field label="Amber lower bound" error={error}><Input type="number" step="any" value={Number.isFinite(lower) ? lower : ""} onChange={(event) => setDraft({ ...draft, performanceThreshold: { direction: "target_exactly", amberLowerBound: event.target.value === "" ? Number.NaN : Number(event.target.value), amberUpperBound: upper } })} /></Field><Field label="Amber upper bound" error={error}><Input type="number" step="any" value={Number.isFinite(upper) ? upper : ""} onChange={(event) => setDraft({ ...draft, performanceThreshold: { direction: "target_exactly", amberLowerBound: lower, amberUpperBound: event.target.value === "" ? Number.NaN : Number(event.target.value) } })} /></Field></>}</div>}{presentation && targetReady ? <div className="mt-4 grid gap-px overflow-hidden rounded-lg border bg-border sm:grid-cols-3"><ThresholdStatus label="Green" value={presentation.green} tone="green" /><ThresholdStatus label="Amber" value={presentation.amber} tone="amber" /><ThresholdStatus label="Red" value={presentation.red} tone="red" /></div> : <div className="mt-4 rounded-lg bg-muted/35 px-3 py-2 text-xs">Complete the target and warning boundary to preview performance thresholds.</div>}</section>;
}

function Preview({ draft, parent, owner, compact = false }: { draft: Draft; parent?: VisualManagementKpiDefinition; owner?: string; compact?: boolean }) { return <div className="grid gap-5"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-semibold">{draft.name || "KPI name not provided"}</h3><Badge variant="outline">{KPI_BUCKET_LABELS[draft.bucket]} · {draft.level === "unit" ? "Unit KPI" : "Functional KPI"}</Badge></div><p className="mt-4 text-sm leading-6">{draft.smartObjective || "SMART objective not provided"}</p></div>{draft.level === "functional" && parent && <div className="rounded-xl border bg-muted/20 p-4 text-center"><p className="text-xs font-semibold uppercase text-muted-foreground">Functional KPI</p><p className="mt-1 font-semibold">{draft.name}</p><p className="text-xs text-muted-foreground">{KPI_BUCKET_LABELS[draft.bucket]} · {KPI_INDICATOR_TYPE_LABELS[draft.indicatorType]}</p><p className="my-3 text-xs font-semibold uppercase text-primary">contributes to ↑</p><p className="text-xs font-semibold uppercase text-muted-foreground">Unit KPI</p><p className="mt-1 font-semibold">{parent.name}</p>{draft.relationshipExplanation && <p className="mx-auto mt-3 max-w-xl text-xs text-muted-foreground">AI-assisted explanation: {draft.relationshipExplanation}</p>}</div>}<div className="grid gap-4 rounded-xl border p-4 sm:grid-cols-2 lg:grid-cols-4"><Meta label="Indicator" value={KPI_INDICATOR_TYPE_LABELS[draft.indicatorType]} /><Meta label="Measurement" value={KPI_MEASUREMENT_LABELS[draft.measurementType]} /><Meta label="Direction" value={KPI_DIRECTION_LABELS[draft.direction]} /><Meta label="Baseline" value={formatKpiNumericValue(draft.baseline, draft.measurementType)} /><Meta label="Target" value={Number.isFinite(draft.target) ? targetText(draft as VisualManagementKpiDefinition) : "Not provided"} /><Meta label="Target Date" value={date(draft.targetDate)} />{draft.functionName && <Meta label="Function" value={draft.functionName} />}{draft.level === "functional" && <Meta label="Owner" value={owner ?? (draft.ownerUserId ? "Inactive or unavailable user" : "Not selected")} />}{draft.reviewFrequency && <Meta label="Review Frequency" value={KPI_REVIEW_FREQUENCY_LABELS[draft.reviewFrequency]} />}</div>{!compact && <ThresholdFields draft={draft} setDraft={() => undefined} readOnly />}</div>; }

function KpiDetail({ item, parent, descendantKpis, owner, onClose, onEdit, onArchive, onAddChild }: { item: VisualManagementKpiDefinition; parent?: VisualManagementKpiDefinition; descendantKpis: VisualManagementKpiDefinition[]; owner?: string; onClose: () => void; onEdit: () => void; onArchive: () => void; onAddChild: () => void }) { return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="max-h-[calc(100dvh-1rem)] max-w-3xl overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{item.name}</DialogTitle><DialogDescription>{KPI_BUCKET_LABELS[item.bucket]} · {item.level === "unit" ? "Unit KPI" : "Functional KPI"}</DialogDescription></DialogHeader><p className="text-sm leading-6">{item.smartObjective}</p><div className="grid gap-4 border-y py-4 sm:grid-cols-3"><Meta label="Indicator" value={KPI_INDICATOR_TYPE_LABELS[item.indicatorType]} /><Meta label="Measurement" value={KPI_MEASUREMENT_LABELS[item.measurementType]} /><Meta label="Direction" value={KPI_DIRECTION_LABELS[item.direction]} /><Meta label="Baseline" value={formatKpiNumericValue(item.baseline, item.measurementType)} /><Meta label="Target" value={targetText(item)} /><Meta label="Target Date" value={date(item.targetDate)} />{parent && <Meta label="Parent Unit KPI" value={parent.name} />}{item.functionName && <Meta label="Function" value={item.functionName} />}{item.ownerUserId && <Meta label="Owner" value={owner ?? "Inactive or unavailable user"} />}{item.reviewFrequency && <Meta label="Review Frequency" value={KPI_REVIEW_FREQUENCY_LABELS[item.reviewFrequency]} />}</div><ThresholdFields draft={item} setDraft={() => undefined} readOnly />{item.level === "unit" && <section><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Functional KPIs contributing to this KPI</h3><Button size="sm" variant="outline" onClick={onAddChild}><Plus className="size-3.5" />Add Functional KPI</Button></div><div className="mt-3 grid gap-2">{descendantKpis.length ? descendantKpis.map((child) => <div key={child.id} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{child.functionName} Function · {KPI_BUCKET_LABELS[child.bucket]} · {KPI_INDICATOR_TYPE_LABELS[child.indicatorType]}</p><p className="text-sm font-semibold">{child.name}</p></div>) : <p className="text-sm text-muted-foreground">No Functional KPIs connected yet.</p>}</div></section>}<DialogFooter><Button variant="ghost" onClick={onArchive}><Archive className="size-4" />Archive</Button><Button variant="outline" onClick={onEdit}><Edit3 className="size-4" />Edit</Button><Button onClick={onClose}>Close</Button></DialogFooter></DialogContent></Dialog>; }
function ThresholdStatus({ label, value, tone }: { label: string; value: string; tone: "green" | "amber" | "red" }) { return <div className="bg-card p-3"><p className={`text-[10px] font-semibold uppercase tracking-wide ${tone === "green" ? "text-emerald-700 dark:text-emerald-400" : tone === "amber" ? "text-amber-700 dark:text-amber-400" : "text-red-700 dark:text-red-400"}`}>{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="grid min-w-0 gap-1.5 text-sm font-medium">{label}{children}<FieldMessage error>{error}</FieldMessage></label>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }
