"use client";
/* eslint-disable @next/next/no-img-element -- report evidence uses uploaded data URLs and local evidence assets. */

import Link from "next/link";
import { ArrowLeft, ImageIcon, Printer } from "lucide-react";
import { PageContainer } from "@/components/layout/page-container";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import FiveSPageHeader from "@/features/five-s/components/FiveSPageHeader";
import { useActionStore } from "@/lib/actions/action-store";
import { ACTION_STATUS_CONFIG } from "@/lib/actions/action-config";
import { formatVisualDate, formatVisualMoney, VisualImprovementStatusBadge } from "./visual-improvement-components";
import { useVisualImprovements } from "./visual-improvement-store";
import type { VisualImprovementEvidence } from "./types";

export default function VisualImprovementReportPage({ improvementId }: { improvementId: string }) {
  const item = useVisualImprovements().find((record) => record.id === improvementId);
  const actions = useActionStore();
  if (!item || item.status !== "Completed") return <PageContainer><FiveSPageHeader eyebrow="Visual Improvement / Report" title="Completed report not found" description="Reports are available after an improvement has been approved." /><Button className="w-fit" variant="outline" nativeButton={false} render={<Link href="/visual-improvement" />}>Back to Visual Improvement</Button></PageContainer>;
  const action = item.actionId ? actions.find((candidate) => candidate.id === item.actionId) : undefined;
  return <PageContainer className="max-w-none">
    <style>{`@media print{@page{size:A4 landscape;margin:8mm}.vi-report-actions{display:none!important}.vi-report-document{border:0!important;box-shadow:none!important}.vi-print-block{break-inside:avoid;page-break-inside:avoid}body{background:white!important}}`}</style>
    <div className="vi-report-actions"><FiveSPageHeader eyebrow={`Visual Improvement / ${item.id}`} title="Improvement Report" description="Print or save this completed transformation as PDF." leading={<Button size="icon-sm" variant="ghost" nativeButton={false} render={<Link href={`/visual-improvement/${encodeURIComponent(item.id)}`} />} aria-label="Back to improvement"><ArrowLeft className="size-4" /></Button>} actions={<Button onClick={() => window.print()}><Printer className="size-4" />Print / Save PDF</Button>} /></div>
    <article className="vi-report-document mx-auto max-w-[1180px] overflow-hidden rounded-xl border border-slate-200 bg-white text-slate-950 shadow-sm dark:border-slate-700 dark:bg-slate-900 dark:text-white">
      <header className="vi-print-block border-b border-blue-100 bg-gradient-to-b from-blue-50/70 to-white px-6 py-5 text-center dark:border-slate-700 dark:from-blue-950/30 dark:to-slate-900"><VisualImprovementStatusBadge status={item.status} /><p className="mt-3 text-2xl font-extrabold uppercase tracking-[.08em] text-blue-800 dark:text-blue-300">Visual Improvement Report</p><p className="mt-2 font-mono text-xs text-blue-700 dark:text-blue-400">{item.id}</p><h1 className="mx-auto mt-2 max-w-4xl text-2xl font-extrabold">{item.title}</h1></header>
      <div className="grid gap-4 p-5">
        <section className="vi-print-block grid gap-px overflow-hidden rounded-lg border border-blue-200 bg-blue-100 dark:border-slate-700 dark:bg-slate-700 sm:grid-cols-4"><ReportMeta label="Plant" value={item.plant} /><ReportMeta label="Zone" value={item.zone} /><ReportMeta label="Category" value={item.category} /><ReportMeta label="Location" value={item.location} /><ReportMeta label="Owner" value={item.ownerName} /><ReportMeta label="Participants" value={item.participants.map((person) => person.name).join(", ") || "None"} /><ReportMeta label="Created" value={formatVisualDate(item.createdAt)} /><ReportMeta label="Completed" value={formatVisualDate(item.completedAt)} /></section>
        <section className="vi-print-block grid gap-4 md:grid-cols-2"><ReportEvidence label="Before" evidence={item.beforeEvidence[0]} description={item.beforeDescription} tone="before" /><ReportEvidence label="After" evidence={item.afterEvidence[0]} description={item.afterDescription || "Improvement completed"} tone="after" /></section>
        <section className="vi-print-block grid gap-3 sm:grid-cols-3"><ReportStat label="Proposed Saving" value={formatVisualMoney(item.proposedCostSaving)} /><ReportStat label="Actual Saving" value={formatVisualMoney(item.actualCostSaving)} positive /><ReportStat label="Benefit" value={item.benefitDescription || item.expectedBenefit} compact /></section>
        <section className="vi-print-block grid gap-3 md:grid-cols-3"><ReportText title="Expected Benefit" text={item.expectedBenefit} /><ReportText title="Measured Benefits" text={[item.timeSaved && `Time: ${item.timeSaved}`, item.spaceSaved && `Space: ${item.spaceSaved}`, item.safetyBenefit && `Safety: ${item.safetyBenefit}`, item.qualityBenefit && `Quality: ${item.qualityBenefit}`, item.otherBenefit].filter(Boolean).join(" · ") || item.benefitDescription || "Non-financial benefit recorded"} /><ReportText title="Completion Notes" text={item.completionNotes || "No additional completion notes."} /></section>
        <section className="vi-print-block grid gap-4 border-t pt-4 md:grid-cols-2"><div><h2 className="text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">Linked Action</h2>{action ? <div className="mt-2 rounded-lg border p-3"><div className="flex items-center justify-between gap-3"><p className="font-mono text-xs font-semibold">{action.id}</p><Badge variant={ACTION_STATUS_CONFIG[action.status].variant}>{action.status}</Badge></div><p className="mt-2 text-sm font-semibold">{action.title}</p><p className="mt-1 text-xs text-slate-500">{action.responsiblePersonName || action.assignedTo} · {action.priority} · Due {formatVisualDate(action.dueDate)}</p></div> : <p className="mt-2 rounded-lg border border-dashed p-3 text-xs text-slate-500">No Action Required</p>}</div><div><h2 className="text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">Completion Details</h2><div className="mt-2 grid grid-cols-2 gap-px overflow-hidden rounded-lg border bg-slate-200 dark:bg-slate-700"><ReportMeta label="Completed By" value={item.completedByName || item.ownerName} /><ReportMeta label="Reviewed By" value={item.reviewedByName || "—"} /><ReportMeta label="Completed Date" value={formatVisualDate(item.completedAt, true)} /><ReportMeta label="Reviewed Date" value={formatVisualDate(item.reviewedAt, true)} /></div></div></section>
        <section className="vi-print-block border-t pt-4"><h2 className="text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">Timeline Summary</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{item.activity.map((entry) => <div key={entry.id} className="rounded-lg border p-3"><p className="text-xs font-semibold">{entry.label}</p><p className="mt-1 text-[10px] text-slate-500">{entry.actorName} · {formatVisualDate(entry.at, true)}</p>{entry.remark && <p className="mt-1 text-[10px] leading-4 text-slate-500">{entry.remark}</p>}</div>)}</div></section>
      </div>
    </article>
  </PageContainer>;
}

function ReportEvidence({ label, evidence, description, tone }: { label: string; evidence?: VisualImprovementEvidence; description: string; tone: "before" | "after" }) { return <figure className="overflow-hidden rounded-lg border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><div className={`py-2 text-center text-xs font-bold uppercase tracking-wider text-white ${tone === "before" ? "bg-amber-600" : "bg-emerald-600"}`}>{label}</div>{evidence ? <img src={evidence.url} alt={evidence.caption || evidence.name} className="aspect-[16/9] w-full object-cover" /> : <div className="grid aspect-[16/9] place-items-center bg-slate-50 text-slate-400 dark:bg-slate-800"><ImageIcon className="size-6" /></div>}<figcaption className="min-h-16 p-3 text-center text-xs font-medium leading-5 text-slate-600 dark:text-slate-300">{description}</figcaption></figure>; }
function ReportMeta({ label, value }: { label: string; value: string }) { return <div className="bg-white p-3 dark:bg-slate-900"><p className="text-[9px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div>; }
function ReportStat({ label, value, positive, compact }: { label: string; value: string; positive?: boolean; compact?: boolean }) { return <div className="rounded-lg border border-blue-100 bg-blue-50/30 p-4 text-center dark:border-slate-700 dark:bg-slate-800/30"><p className={`${compact ? "text-sm leading-5" : "text-2xl"} font-extrabold ${positive ? "text-emerald-700 dark:text-emerald-400" : "text-blue-800 dark:text-blue-300"}`}>{value}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p></div>; }
function ReportText({ title, text }: { title: string; text: string }) { return <div className="rounded-lg border border-blue-100 p-4 dark:border-slate-700"><p className="text-[10px] font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">{title}</p><p className="mt-2 text-xs font-medium leading-5 text-slate-600 dark:text-slate-300">{text}</p></div>; }
