"use client";

import { useSyncExternalStore } from "react";
import { safeSetStorage } from "@/lib/browser-storage";
import { evaluateKpiPerformance, validatePerformanceThreshold, type KpiDirection, type KpiMeasurementType, type KpiPerformanceStatus, type KpiPerformanceThreshold } from "./kpi-configuration";
import { getVisualManagementKpi } from "./kpi-configuration-store";
import { normalizedReportingPeriodKey } from "./reporting-period";

export type KpiReportingPeriodType = "daily" | "weekly" | "monthly" | "custom";
export interface KpiReportingPeriod { type: KpiReportingPeriodType; key: string; label: string }
export interface VisualManagementKpiAssignment { id: string; boardId: string; kpiId: string; displayOrder: number; isVisible: boolean; assignedAt: string; assignedByUserId: string }
export interface KpiActualEntry { id: string; kpiId: string; boardId: string; value: number; reportingPeriod: KpiReportingPeriod; reportedAt: string; reportedByUserId: string; comment?: string; statusSnapshot: Exclude<KpiPerformanceStatus, "unavailable">; targetSnapshot: number; thresholdSnapshot: KpiPerformanceThreshold; measurementSnapshot: KpiMeasurementType; directionSnapshot: KpiDirection; createdAt: string }
export interface KpiDeviation { id: string; kpiActualEntryId: string; kpiId: string; boardId: string; status: "amber" | "red"; comment: string; correctiveActionRequired: boolean; noActionJustification?: string; actionId?: string; createdByUserId: string; createdAt: string }
export interface MeetingKpiReviewSnapshot { id: string; meetingId: string; boardId: string; kpiId: string; kpiActualEntryId?: string; kpiNameSnapshot: string; kpiLevelSnapshot: "unit" | "functional"; bucketSnapshot: string; reportingPeriodSnapshot?: KpiReportingPeriod; actualSnapshot?: number; targetSnapshot: number; statusSnapshot: KpiPerformanceStatus; deviationSnapshot?: string; correctiveActionRequiredSnapshot?: boolean; noActionJustificationSnapshot?: string; actionId?: string; reviewedAt: string; reviewedByUserId: string }
interface ExecutionState { assignments: VisualManagementKpiAssignment[]; actualEntries: KpiActualEntry[]; deviations: KpiDeviation[] }

const STORAGE_KEY = "ops-visual-management-kpi-execution-v1";
const EMPTY: ExecutionState = { assignments: [], actualEntries: [], deviations: [] };
let state = EMPTY; let loaded = false; const listeners = new Set<() => void>();
function uid(prefix: string) { return `${prefix}-${globalThis.crypto?.randomUUID?.().slice(0, 8) ?? Date.now()}`; }
function load() { if (loaded || typeof window === "undefined") return; loaded = true; try { const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "null") as Partial<ExecutionState> | null; state = parsed ? { assignments: Array.isArray(parsed.assignments) ? parsed.assignments : [], actualEntries: Array.isArray(parsed.actualEntries) ? parsed.actualEntries : [], deviations: Array.isArray(parsed.deviations) ? parsed.deviations : [] } : EMPTY; } catch { state = EMPTY; } }
function snapshot() { load(); return state; } function subscribe(listener: () => void) { load(); listeners.add(listener); return () => listeners.delete(listener); }
function persist(next: ExecutionState) { const previous = state; state = next; const result = typeof window === "undefined" ? { success: true } : safeSetStorage(STORAGE_KEY, next); if (!result.success) { state = previous; return false; } listeners.forEach((listener) => listener()); return true; }
export function useKpiExecution() { return useSyncExternalStore(subscribe, snapshot, () => EMPTY); }
export function getKpiExecution() { return snapshot(); }
export function assignKpiToBoard(boardId: string, kpiId: string, assignedByUserId: string) { const current = snapshot(); const kpi = getVisualManagementKpi(kpiId); if (!boardId || !assignedByUserId) return { success: false as const, error: "Board and assigning user are required." }; if (!kpi || kpi.status !== "active") return { success: false as const, error: "Only active configured KPIs can be assigned." }; const existing = current.assignments.find((item) => item.boardId === boardId && item.kpiId === kpiId); if (existing?.isVisible) return { success: false as const, error: "This KPI is already assigned to the board." }; const now = new Date().toISOString(); const assignment: VisualManagementKpiAssignment = existing ? { ...existing, isVisible: true, assignedAt: now, assignedByUserId } : { id: uid("VMKA"), boardId, kpiId, displayOrder: current.assignments.filter((item) => item.boardId === boardId && item.isVisible).length, isVisible: true, assignedAt: now, assignedByUserId }; const next = existing ? current.assignments.map((item) => item.id === existing.id ? assignment : item) : [...current.assignments, assignment]; return persist({ ...current, assignments: next }) ? { success: true as const, assignment } : { success: false as const, error: "Assignment could not be saved." }; }
export function unassignKpiFromBoard(boardId: string, kpiId: string) { const current = snapshot(); const existing = current.assignments.find((item) => item.boardId === boardId && item.kpiId === kpiId && item.isVisible); if (!existing) return false; return persist({ ...current, assignments: current.assignments.map((item) => item.id === existing.id ? { ...item, isVisible: false } : item) }); }
export function getLatestActual(boardId: string, kpiId: string) { return snapshot().actualEntries.filter((item) => item.boardId === boardId && item.kpiId === kpiId).sort((a, b) => b.reportedAt.localeCompare(a.reportedAt))[0]; }
export function submitKpiActual(input: { boardId: string; kpiId: string; value: number; reportingPeriod: KpiReportingPeriod; reportedByUserId: string; comment?: string; deviationComment?: string; correctiveActionRequired?: boolean; noActionJustification?: string }) {
  const current = snapshot(); const kpi = getVisualManagementKpi(input.kpiId); if (!kpi) return { success: false as const, error: "Configured KPI is unavailable." }; if (kpi.status !== "active") return { success: false as const, error: "Archived KPIs cannot accept new actuals." }; if (!current.assignments.some((item) => item.boardId === input.boardId && item.kpiId === input.kpiId && item.isVisible)) return { success: false as const, error: "KPI is not assigned to this board." }; if (!input.reportingPeriod.key.trim() || !input.reportingPeriod.label.trim()) return { success: false as const, error: "Reporting period is required." }; if (!input.reportedByUserId) return { success: false as const, error: "Reporting user is required." }; const normalizedKey = normalizedReportingPeriodKey(input.reportingPeriod); if (current.actualEntries.some((item) => item.boardId === input.boardId && item.kpiId === input.kpiId && item.reportingPeriod.type === input.reportingPeriod.type && normalizedReportingPeriodKey(item.reportingPeriod) === normalizedKey)) return { success: false as const, error: `${input.reportingPeriod.label} already has a reported actual for this board and KPI.` };
  const thresholdError = validatePerformanceThreshold(kpi.direction, kpi.target, kpi.performanceThreshold); if (thresholdError) return { success: false as const, error: thresholdError }; const status = evaluateKpiPerformance(input.value, kpi.measurementType, kpi.direction, kpi.target, kpi.performanceThreshold); if (status === "unavailable") return { success: false as const, error: "Actual value or performance configuration is invalid." };
  if (status !== "green" && !input.deviationComment?.trim()) return { success: false as const, error: "Deviation comment is required for Amber or Red performance." }; if (status !== "green" && input.correctiveActionRequired === undefined) return { success: false as const, error: "Confirm whether corrective action is required." }; if (status !== "green" && input.correctiveActionRequired === false && !input.noActionJustification?.trim()) return { success: false as const, error: "Explain why corrective action is not required." };
  const now = new Date().toISOString(); const entry: KpiActualEntry = { id: uid("VMKAE"), boardId: input.boardId, kpiId: input.kpiId, value: input.value, reportingPeriod: { ...input.reportingPeriod }, reportedAt: now, reportedByUserId: input.reportedByUserId, comment: input.comment?.trim() || undefined, statusSnapshot: status, targetSnapshot: kpi.target, thresholdSnapshot: { ...kpi.performanceThreshold! }, measurementSnapshot: kpi.measurementType, directionSnapshot: kpi.direction, createdAt: now };
  const deviation: KpiDeviation | undefined = status === "green" ? undefined : { id: uid("VMKD"), kpiActualEntryId: entry.id, kpiId: input.kpiId, boardId: input.boardId, status, comment: input.deviationComment!.trim(), correctiveActionRequired: input.correctiveActionRequired!, noActionJustification: input.correctiveActionRequired ? undefined : input.noActionJustification!.trim(), createdByUserId: input.reportedByUserId, createdAt: now };
  return persist({ ...current, actualEntries: [...current.actualEntries, entry], deviations: deviation ? [...current.deviations, deviation] : current.deviations }) ? { success: true as const, entry, deviation } : { success: false as const, error: "Actual could not be saved." };
}
export function linkDeviationAction(deviationId: string, actionId: string) { const current = snapshot(); const deviation = current.deviations.find((item) => item.id === deviationId); if (!deviation || deviation.actionId || !actionId) return false; return persist({ ...current, deviations: current.deviations.map((item) => item.id === deviationId ? { ...item, actionId } : item) }); }
export function createMeetingKpiReviewSnapshots(meetingId: string, boardId: string, reviewedByUserId: string): MeetingKpiReviewSnapshot[] { const current = snapshot(); return current.assignments.filter((item) => item.boardId === boardId && item.isVisible).flatMap((assignment) => { const kpi = getVisualManagementKpi(assignment.kpiId); if (!kpi) return []; const entry = getLatestActual(boardId, kpi.id); const deviation = entry ? current.deviations.find((item) => item.kpiActualEntryId === entry.id) : undefined; return [{ id: uid("VMKR"), meetingId, boardId, kpiId: kpi.id, kpiActualEntryId: entry?.id, kpiNameSnapshot: kpi.name, kpiLevelSnapshot: kpi.level, bucketSnapshot: kpi.bucket, reportingPeriodSnapshot: entry ? { ...entry.reportingPeriod } : undefined, actualSnapshot: entry?.value, targetSnapshot: entry?.targetSnapshot ?? kpi.target, statusSnapshot: entry?.statusSnapshot ?? "unavailable", deviationSnapshot: deviation?.comment, correctiveActionRequiredSnapshot: deviation?.correctiveActionRequired, noActionJustificationSnapshot: deviation?.noActionJustification, actionId: deviation?.actionId, reviewedAt: new Date().toISOString(), reviewedByUserId }]; }); }
export function setKpiExecutionForTests(next: ExecutionState) { state = next; loaded = true; }
