"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowLeft, Check, ChevronDown, CirclePlay, ClipboardCheck, DoorOpen, Flag, Footprints, Lightbulb, ListTodo, MessageSquarePlus, Plus, Save, Sparkles, UserPlus, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { CreateLinkedActionDialog, type LinkedActionContext } from "@/features/actions/create-linked-action-dialog";
import { useAdminUsers } from "@/features/five-s/administration/store";
import { useActionStore } from "@/lib/actions/action-store";
import { useCurrentUser } from "@/lib/current-user";
import { useModuleEntitlements } from "@/lib/module-entitlements";
import { cn } from "@/lib/utils";
import type { MyAction } from "@/features/five-s/types/my-actions";
import { VISUAL_MANAGEMENT_KPI_STATUSES } from "./visual-management-config";
import { canViewVisualManagementBoard } from "./visual-management-access";
import { EscalationStatusBadge, KpiStatusBadge } from "./visual-management-components";
import {
  addMeetingDecision,
  addMeetingGuest,
  addMeetingTopic,
  completeVisualManagementMeeting,
  createMeetingEscalation,
  getEscalationTargets,
  linkTopicFollowUp,
  meetingDurationMinutes,
  setMeetingAttendance,
  startVisualManagementMeeting,
  updateMeetingKpi,
  useVisualManagementStore,
} from "./visual-management-store";
import type { VisualManagementKpiSection, VisualManagementMeeting, VisualManagementPerson, VisualManagementTopic } from "./types";

export default function MeetingModePage({ boardId }: { boardId: string }) {
  const state = useVisualManagementStore();
  const currentUser = useCurrentUser();
  const adminUser = useAdminUsers().find((user) => user.id === currentUser.id);
  const candidate = state.boards.find((item) => item.id === boardId);
  const board = candidate && canViewVisualManagementBoard(candidate, currentUser, adminUser?.roles) ? candidate : undefined;
  const activeMeeting = state.meetings.find((item) => item.boardId === boardId && item.status === "In Progress");
  if (!board) return <div className="p-8"><p className="text-sm">Board not found.</p><Button className="mt-4" variant="outline" nativeButton={false} render={<Link href="/visual-management/boards" />}>Back to Boards</Button></div>;
  if (activeMeeting) return <LiveMeeting meeting={activeMeeting} />;
  if (board.status !== "Active") return <div className="p-8"><p className="text-sm">This Board is inactive and cannot start a new meeting.</p><Button className="mt-4" variant="outline" nativeButton={false} render={<Link href={`/visual-management/boards/${board.id}`} />}>Back to Board</Button></div>;
  return <MeetingConfirmation boardId={boardId} />;
}

function MeetingConfirmation({ boardId }: { boardId: string }) {
  const state = useVisualManagementStore();
  const board = state.boards.find((item) => item.id === boardId)!;
  const currentUser = useCurrentUser();
  const [leadId, setLeadId] = useState(board.members.some((person) => person.id === currentUser.id) ? currentUser.id : board.owner.id);
  const lead = board.members.find((person) => person.id === leadId) ?? board.owner;
  return <div className="fixed inset-0 z-[90] overflow-y-auto bg-background"><header className="sticky top-0 z-10 border-b bg-background/95 px-4 py-3 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-5xl items-center gap-3"><Button variant="ghost" size="icon-sm" nativeButton={false} render={<Link href={`/visual-management/boards/${board.id}`} />} aria-label="Exit meeting mode"><ArrowLeft className="size-4" /></Button><div><p className="text-sm font-semibold">Prepare Meeting</p><p className="text-xs text-muted-foreground">Visual Management · {board.tier}</p></div></div></header><main className="mx-auto grid max-w-3xl gap-5 p-4 sm:p-8"><div className="text-center"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><CirclePlay className="size-6" /></span><h1 className="mt-4 text-2xl font-semibold">{board.name}</h1><p className="mt-1 text-sm text-muted-foreground">Confirm the meeting details. Known board data is already populated.</p></div><Card className="gap-0"><CardContent className="grid gap-5 p-5 sm:grid-cols-2"><Meta label="Board" value={board.name} /><Meta label="Plant / Zone" value={`${board.plant} / ${board.zone ?? "All zones"}`} /><Meta label="Tier" value={board.tier} /><Meta label="Date / Start" value={new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date())} /><label className="grid gap-2 text-sm font-medium sm:col-span-2">Meeting lead<Select value={lead.id} onValueChange={(value) => setLeadId(value ?? board.owner.id)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{board.members.map((person) => <SelectItem key={person.id} value={person.id}>{person.name}</SelectItem>)}</SelectContent></Select></label><div className="sm:col-span-2"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Expected participants</p><div className="mt-2 flex flex-wrap gap-2">{board.members.map((person) => <Badge key={person.id} variant="secondary">{person.name}</Badge>)}</div></div></CardContent></Card><Button className="min-h-12" onClick={() => startVisualManagementMeeting(board.id, lead)}><CirclePlay className="size-4" />Start Meeting Mode</Button></main></div>;
}

function LiveMeeting({ meeting }: { meeting: VisualManagementMeeting }) {
  const state = useVisualManagementStore();
  const actions = useActionStore();
  const access = useModuleEntitlements();
  const currentUser = useCurrentUser();
  const router = useRouter();
  const board = state.boards.find((item) => item.id === meeting.boardId)!;
  const topics = state.topics.filter((item) => meeting.topicIds.includes(item.id));
  const decisions = state.decisions.filter((item) => meeting.decisionIds.includes(item.id));
  const escalations = state.escalations.filter((item) => meeting.escalationIds.includes(item.id));
  const relevantActions = useMemo(() => {
    const actionIds = new Set(meeting.actionIds);
    return actions
      .filter((action) => actionIds.has(action.id) || (action.area === meeting.zone && action.status !== "Completed"))
      .sort((a, b) => actionPriority(a.status, a.dueDate) - actionPriority(b.status, b.dueDate));
  }, [actions, meeting.actionIds, meeting.zone]);
  const [guestOpen, setGuestOpen] = useState(false);
  const [guestName, setGuestName] = useState("");
  const [topicOpen, setTopicOpen] = useState(false);
  const [decisionOpen, setDecisionOpen] = useState(false);
  const [selectedTopic, setSelectedTopic] = useState<VisualManagementTopic | null>(null);
  const [actionOpen, setActionOpen] = useState(false);
  const [escalationOpen, setEscalationOpen] = useState(false);
  const [completeOpen, setCompleteOpen] = useState(false);
  const present = meeting.participants.filter((person) => person.attendance === "Present").length;
  const redCount = meeting.kpiEntries.filter((entry) => entry.status === "Red").length;

  const actionContext: LinkedActionContext | null = selectedTopic ? {
    source: "Visual Management",
    sourceModule: "visualManagement",
    sourceId: meeting.id,
    sourceObservationId: selectedTopic.id,
    sourceObservation: selectedTopic.title,
    title: selectedTopic.title,
    description: `${selectedTopic.description}\n\nBoard: ${board.name} (${board.id})\nMeeting: ${meeting.id}\nKPI section: ${selectedTopic.section}`,
    plant: meeting.plant,
    zone: meeting.zone ?? "Zone A",
    location: `${board.name} · ${board.id}`,
    evidence: [],
    defaultPriority: selectedTopic.section === "Safety" ? "High" : "Medium",
  } : null;

  function routeFollowUp(topic: VisualManagementTopic, type: "Red Flag" | "Continuous Improvement" | "Gemba") {
    linkTopicFollowUp(topic.id, type);
    const query = new URLSearchParams({ source: "visual-management", meetingId: meeting.id, topicId: topic.id, title: topic.title, description: topic.description, plant: meeting.plant, zone: meeting.zone ?? "Zone A", section: topic.section });
    const path = type === "Red Flag" ? "/red-flag/new" : type === "Continuous Improvement" ? "/continuous-improvement/new" : "/gemba/new";
    router.push(`${path}?${query.toString()}`);
  }

  return <div className="fixed inset-0 z-[90] flex flex-col bg-background text-foreground"><header className="shrink-0 border-b bg-card px-3 py-3 shadow-sm sm:px-5"><div className="mx-auto flex max-w-[1680px] flex-wrap items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><ClipboardCheck className="size-4" /></span><div className="min-w-0 flex-1"><h1 className="truncate text-sm font-semibold sm:text-base">{board.name} · {board.tier} Meeting</h1><p className="mt-0.5 text-[11px] text-muted-foreground">{new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(meeting.startedAt))} · Lead: {meeting.lead.name} · {present} Participants</p></div><Badge variant={redCount ? "danger" : "success"}>{redCount ? `${redCount} Red KPI` : "KPIs on track"}</Badge><Button variant="outline" size="sm" nativeButton={false} render={<Link href={`/visual-management/boards/${board.id}`} />}><DoorOpen className="size-4" />Exit Meeting Mode</Button></div></header>
    <main className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto grid max-w-[1680px] gap-4 p-3 pb-28 sm:p-5 sm:pb-28 xl:grid-cols-12">
      <section className="grid content-start gap-4 xl:col-span-9">
        <MeetingSection icon={Users} title="Attendance" badge={`${present}/${meeting.participants.length} present`}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{meeting.participants.map((person) => <button type="button" onClick={() => setMeetingAttendance(meeting.id, person.id, person.attendance === "Present" ? "Absent" : "Present")} key={person.id} className={cn("flex min-h-11 items-center gap-3 rounded-lg border px-3 text-left", person.attendance === "Present" ? "border-emerald-500/25 bg-emerald-500/[0.06]" : "bg-muted/20")}><span className={cn("grid size-5 place-items-center rounded-full border", person.attendance === "Present" && "border-emerald-500 bg-emerald-500 text-white")}>{person.attendance === "Present" && <Check className="size-3" />}</span><span className="min-w-0 flex-1 truncate text-sm font-medium">{person.name}{person.guest ? " · Guest" : ""}</span></button>)}</div><Button className="mt-3" variant="outline" size="sm" onClick={() => setGuestOpen(true)}><UserPlus className="size-3.5" />Guest</Button></MeetingSection>
        <MeetingSection icon={ClipboardCheck} title="KPI Review" badge={`${meeting.kpiEntries.filter((entry) => entry.status === "Green").length}/${meeting.kpiEntries.length} green`}><div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-5">{meeting.kpiEntries.map((entry) => <Card key={entry.section} className={cn("gap-0 shadow-none", entry.status === "Red" && "border-red-500/30", entry.status === "Amber" && "border-amber-500/30")}><CardHeader className="flex-row items-center justify-between border-b pb-3"><CardTitle className="text-sm">{entry.section}</CardTitle><KpiStatusBadge status={entry.status} /></CardHeader><CardContent className="grid gap-3 p-3"><Field label="Status"><Select value={entry.status} onValueChange={(value) => updateMeetingKpi(meeting.id, entry.section, { status: (value ?? "Green") as typeof entry.status })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{VISUAL_MANAGEMENT_KPI_STATUSES.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></Field><Field label="Target"><Input value={entry.target} onChange={(event) => updateMeetingKpi(meeting.id, entry.section, { target: event.target.value })} /></Field><Field label="Actual"><Input value={entry.actual} onChange={(event) => updateMeetingKpi(meeting.id, entry.section, { actual: event.target.value })} /></Field><Field label="Note"><Textarea value={entry.note} rows={2} placeholder="Exception or update" onChange={(event) => updateMeetingKpi(meeting.id, entry.section, { note: event.target.value })} /></Field></CardContent></Card>)}</div></MeetingSection>
        <MeetingSection icon={ListTodo} title="Previous Actions" badge={`${relevantActions.filter((action) => action.status !== "Completed").length} open`}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-3 py-2">Action</th><th className="px-3 py-2">Owner</th><th className="px-3 py-2">Due</th><th className="px-3 py-2">Status</th><th className="px-3 py-2 text-right">View</th></tr></thead><tbody className="divide-y">{relevantActions.slice(0, 6).map((action) => <tr key={action.id}><td className="px-3 py-3"><p className="font-medium">{action.title}</p><p className="mt-0.5 font-mono text-[10px] text-muted-foreground">{action.id}</p></td><td className="px-3 py-3">{action.responsiblePersonName ?? action.assignedTo}</td><td className={cn("px-3 py-3", action.status === "Overdue" && "font-semibold text-red-600 dark:text-red-400")}>{action.dueDate}</td><td className="px-3 py-3"><Badge variant={action.status === "Completed" ? "success" : action.status === "Overdue" ? "danger" : "warning"}>{action.status}</Badge></td><td className="px-3 py-3 text-right"><Button size="sm" variant="ghost" nativeButton={false} render={<Link href={`/actions/${action.id}`} target="_blank" />}>View Action</Button></td></tr>)}</tbody></table>{!relevantActions.length && <p className="p-5 text-center text-sm text-muted-foreground">No open actions for this board scope.</p>}</div></MeetingSection>
        <MeetingSection icon={MessageSquarePlus} title="Today&apos;s Discussion" badge={`${topics.length} topics`} action={<Button size="sm" onClick={() => setTopicOpen(true)}><Plus className="size-3.5" />Add Topic</Button>}><div className="grid gap-3">{topics.map((topic) => <article key={topic.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start gap-2"><Badge variant="outline">{topic.section}</Badge><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{topic.title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{topic.description}</p>{topic.decision && <p className="mt-2 text-xs"><strong>Decision:</strong> {topic.decision}</p>}{topic.owner && <p className="mt-2 text-[11px] text-muted-foreground">Owner: {topic.owner.name}</p>}</div>{topic.followUpType ? <Badge variant="info">{topic.followUpType}</Badge> : topic.followUpRequired && <Badge variant="warning">Follow-up needed</Badge>}</div><div className="mt-3 flex flex-wrap gap-2 border-t pt-3">{access.actions && <Button size="sm" variant="outline" onClick={() => { setSelectedTopic(topic); setActionOpen(true); }}><ListTodo className="size-3.5" />Create Action</Button>}{access.redFlag && <Button size="sm" variant="outline" onClick={() => routeFollowUp(topic, "Red Flag")}><Flag className="size-3.5" />Raise Red Flag</Button>}{access.continuousImprovement && <Button size="sm" variant="outline" onClick={() => routeFollowUp(topic, "Continuous Improvement")}><Sparkles className="size-3.5" />Create CI</Button>}{access.gemba && <Button size="sm" variant="outline" onClick={() => routeFollowUp(topic, "Gemba")}><Footprints className="size-3.5" />Gemba Follow-up</Button>}{getEscalationTargets(meeting.boardId).length > 0 && <Button size="sm" variant="outline" onClick={() => { setSelectedTopic(topic); setEscalationOpen(true); }}><AlertTriangle className="size-3.5" />Escalate</Button>}<Button size="sm" variant="ghost" onClick={() => linkTopicFollowUp(topic.id, "Information Only")}>Information Only</Button></div></article>)}{!topics.length && <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">No topics yet. Add the first discussion point without leaving the meeting surface.</p>}</div></MeetingSection>
        <MeetingSection icon={Lightbulb} title="Decisions" badge={`${decisions.length} recorded`} action={<Button size="sm" variant="outline" onClick={() => setDecisionOpen(true)}><Plus className="size-3.5" />Add Decision</Button>}><div className="grid gap-2">{decisions.map((decision) => <div key={decision.id} className="flex gap-3 rounded-lg bg-muted/35 p-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-primary/10 text-primary"><Check className="size-3.5" /></span><span><span className="block text-sm">{decision.decision}</span><span className="mt-1 block text-[11px] text-muted-foreground">Owner: {decision.owner?.name ?? "Meeting team"}{decision.linkedActionId ? ` · Action ${decision.linkedActionId}` : ""}</span></span></div>)}{!decisions.length && <p className="text-sm text-muted-foreground">No decisions recorded yet.</p>}</div></MeetingSection>
        <MeetingSection icon={AlertTriangle} title="Escalations" badge={`${escalations.filter((item) => item.status !== "Resolved").length} open`}><div className="grid gap-2">{escalations.map((item) => <div key={item.id} className="flex items-start gap-3 rounded-lg border p-3"><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{item.reason}</span><span className="mt-1 block text-[11px] text-muted-foreground">To {state.boards.find((boardItem) => boardItem.id === item.targetBoardId)?.name}</span></span><EscalationStatusBadge status={item.status} /></div>)}{!escalations.length && <p className="text-sm text-muted-foreground">No escalations raised in this meeting.</p>}</div></MeetingSection>
      </section>
      <aside className="grid content-start gap-4 xl:col-span-3"><Card className="gap-0 xl:sticky xl:top-4"><CardHeader className="border-b pb-4"><CardTitle className="text-[15px]">Meeting Summary</CardTitle></CardHeader><CardContent className="grid gap-3 p-4"><Summary label="Duration" value={`${meetingDurationMinutes(meeting)} min`} /><Summary label="Participants" value={`${present} present`} /><Summary label="KPI status" value={`${redCount} red · ${meeting.kpiEntries.filter((entry) => entry.status === "Amber").length} amber`} /><Summary label="Topics" value={String(topics.length)} /><Summary label="Actions" value={String(meeting.actionIds.length)} /><Summary label="Red Flags / CI" value={`${meeting.redFlagIds.length} / ${meeting.continuousImprovementIds.length}`} /><Summary label="Escalations" value={String(meeting.escalationIds.length)} /><Summary label="Decisions" value={String(meeting.decisionIds.length)} /><Button className="mt-2 min-h-11" onClick={() => setCompleteOpen(true)}><Check className="size-4" />Complete Meeting</Button></CardContent></Card></aside>
    </div></main>
    <div className="fixed inset-x-0 bottom-0 z-[95] border-t bg-card/95 p-3 shadow-[0_-8px_24px_rgba(0,0,0,.08)] backdrop-blur xl:hidden"><div className="mx-auto grid max-w-xl grid-cols-2 gap-2"><Button variant="outline" onClick={() => setTopicOpen(true)}><Plus className="size-4" />Add Topic</Button><Button onClick={() => setCompleteOpen(true)}><Check className="size-4" />Complete</Button></div></div>
    <GuestDialog open={guestOpen} onOpenChange={setGuestOpen} value={guestName} onValue={setGuestName} onSave={() => { addMeetingGuest(meeting.id, guestName); setGuestName(""); setGuestOpen(false); }} />
    <TopicDialog open={topicOpen} onOpenChange={setTopicOpen} meeting={meeting} onSave={(input) => addMeetingTopic(meeting.id, input, { id: currentUser.id, name: currentUser.name })} />
    <DecisionDialog open={decisionOpen} onOpenChange={setDecisionOpen} meeting={meeting} topics={topics} actions={relevantActions} onSave={(text, owner, topicId, actionId) => addMeetingDecision(meeting.id, text, owner, topicId, actionId)} />
    <CreateLinkedActionDialog key={selectedTopic?.id ?? "vm-action"} open={actionOpen} onOpenChange={setActionOpen} context={actionContext} onCreated={(action) => { if (selectedTopic) linkTopicFollowUp(selectedTopic.id, "Action", action.id); }} />
    <EscalationDialog key={selectedTopic?.id ?? "vm-escalation"} open={escalationOpen} onOpenChange={setEscalationOpen} meeting={meeting} topic={selectedTopic} onSave={(target, reason) => { if (selectedTopic) createMeetingEscalation(selectedTopic.id, target, reason, { id: currentUser.id, name: currentUser.name }); }} />
    <CompleteDialog open={completeOpen} onOpenChange={setCompleteOpen} meeting={meeting} topics={topics.length} redCount={redCount} onComplete={() => { const completed = completeVisualManagementMeeting(meeting.id); if (completed) router.push(`/visual-management/meetings/${meeting.id}`); }} />
  </div>;
}

function MeetingSection({ icon: Icon, title, badge, action, children }: { icon: typeof Users; title: string; badge: string; action?: React.ReactNode; children: React.ReactNode }) { return <details open className="group rounded-xl border bg-card shadow-sm"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 marker:hidden"><span className="grid size-8 place-items-center rounded-lg bg-primary/[0.08] text-primary"><Icon className="size-4" /></span><span className="min-w-0 flex-1 text-sm font-semibold">{title}</span><Badge variant="secondary">{badge}</Badge>{action && <span onClick={(event) => event.preventDefault()}>{action}</span>}<ChevronDown className="size-4 text-muted-foreground transition-transform group-open:rotate-180" /></summary><div className="border-t p-3 sm:p-4">{children}</div></details>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-[11px] font-medium text-muted-foreground">{label}{children}</label>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3 border-b pb-2 text-xs last:border-0"><span className="text-muted-foreground">{label}</span><span className="font-semibold">{value}</span></div>; }
function actionPriority(status: string, due: string) { if (status === "Completed") return 4; if (status === "Overdue") return 0; const date = new Date(`${due}T00:00:00`).getTime(); const today = new Date(); today.setHours(0, 0, 0, 0); if (date < today.getTime()) return 0; if (date === today.getTime()) return 1; return 2; }

function GuestDialog({ open, onOpenChange, value, onValue, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; value: string; onValue: (value: string) => void; onSave: () => void }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add Guest</DialogTitle><DialogDescription>Add a guest to this meeting only.</DialogDescription></DialogHeader><label className="grid gap-2 text-sm font-medium">Guest name<Input value={value} onChange={(event) => onValue(event.target.value)} placeholder="Name" /></label><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!value.trim()} onClick={onSave}><UserPlus className="size-4" />Add Guest</Button></DialogFooter></DialogContent></Dialog>; }

function TopicDialog({ open, onOpenChange, meeting, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; meeting: VisualManagementMeeting; onSave: (input: { section: VisualManagementKpiSection; title: string; description: string; owner?: VisualManagementPerson; decision?: string; followUpRequired?: boolean }) => unknown }) {
  const [section, setSection] = useState<VisualManagementKpiSection>(() => meeting.kpiEntries[0]?.section ?? "Safety"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [ownerId, setOwnerId] = useState(""); const [decision, setDecision] = useState(""); const [followUpRequired, setFollowUpRequired] = useState(false);
  function save() { if (!title.trim()) return; onSave({ section, title, description, owner: meeting.participants.find((person) => person.id === ownerId), decision: decision.trim() || undefined, followUpRequired }); setTitle(""); setDescription(""); setOwnerId(""); setDecision(""); setFollowUpRequired(false); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Add Discussion Topic</DialogTitle><DialogDescription>Capture the issue quickly. Choose a follow-up now or after it is added.</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="KPI Section"><Select value={section} onValueChange={(value) => setSection((value ?? meeting.kpiEntries[0]?.section ?? "Safety") as VisualManagementKpiSection)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{meeting.kpiEntries.map((item) => <SelectItem key={item.section} value={item.section}>{item.section}</SelectItem>)}</SelectContent></Select></Field><Field label="Title"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What needs discussion?" /></Field><Field label="Description"><Textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={4} placeholder="Short operational context" /></Field><Field label="Owner (optional)"><Select value={ownerId} onValueChange={(value) => setOwnerId(value ?? "")}><SelectTrigger className="w-full"><SelectValue placeholder="Select owner" /></SelectTrigger><SelectContent>{meeting.participants.map((person) => <SelectItem key={person.id} value={person.id}>{person.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Decision (optional)"><Textarea value={decision} onChange={(event) => setDecision(event.target.value)} rows={2} placeholder="Record a decision made during discussion" /></Field><button type="button" onClick={() => setFollowUpRequired((value) => !value)} className={cn("flex min-h-11 items-center gap-3 rounded-lg border px-3 text-left text-sm", followUpRequired && "border-primary/30 bg-primary/[0.05]")}><span className={cn("grid size-5 place-items-center rounded border", followUpRequired && "border-primary bg-primary text-primary-foreground")}>{followUpRequired && <Check className="size-3.5" />}</span><span><span className="block font-medium">Follow-up required?</span><span className="block text-[11px] text-muted-foreground">Select the appropriate Action, Red Flag, CI, Gemba, or escalation after saving.</span></span></button></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!title.trim()} onClick={save}><Save className="size-4" />Add Topic</Button></DialogFooter></DialogContent></Dialog>;
}

function DecisionDialog({ open, onOpenChange, meeting, topics, actions, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; meeting: VisualManagementMeeting; topics: VisualManagementTopic[]; actions: MyAction[]; onSave: (text: string, owner?: VisualManagementPerson, topicId?: string, actionId?: string) => unknown }) {
  const [text, setText] = useState(""); const [ownerId, setOwnerId] = useState(""); const [topicId, setTopicId] = useState(""); const [actionId, setActionId] = useState("");
  function save() { if (!text.trim()) return; onSave(text, meeting.participants.find((person) => person.id === ownerId), topicId || undefined, actionId || undefined); setText(""); setOwnerId(""); setTopicId(""); setActionId(""); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Record Decision</DialogTitle><DialogDescription>Record a lightweight meeting decision without forcing an Action.</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Decision"><Textarea value={text} onChange={(event) => setText(event.target.value)} rows={4} placeholder="What did the meeting decide?" /></Field><Field label="Owner (optional)"><Select value={ownerId} onValueChange={(value) => setOwnerId(value ?? "")}><SelectTrigger className="w-full"><SelectValue placeholder="Select owner" /></SelectTrigger><SelectContent>{meeting.participants.map((person) => <SelectItem key={person.id} value={person.id}>{person.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Related topic (optional)"><Select value={topicId} onValueChange={(value) => setTopicId(value ?? "")}><SelectTrigger className="w-full"><SelectValue placeholder="Select topic" /></SelectTrigger><SelectContent>{topics.map((topic) => <SelectItem key={topic.id} value={topic.id}>{topic.title}</SelectItem>)}</SelectContent></Select></Field><Field label="Linked Action (optional)"><Select value={actionId} onValueChange={(value) => setActionId(value ?? "")}><SelectTrigger className="w-full"><SelectValue placeholder="Select action" /></SelectTrigger><SelectContent>{actions.map((action) => <SelectItem key={action.id} value={action.id}>{action.id} · {action.title}</SelectItem>)}</SelectContent></Select></Field></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!text.trim()} onClick={save}><Lightbulb className="size-4" />Record Decision</Button></DialogFooter></DialogContent></Dialog>;
}

function EscalationDialog({ open, onOpenChange, meeting, topic, onSave }: { open: boolean; onOpenChange: (open: boolean) => void; meeting: VisualManagementMeeting; topic: VisualManagementTopic | null; onSave: (target: string, reason: string) => void }) {
  const targets = getEscalationTargets(meeting.boardId); const [target, setTarget] = useState(targets[0]?.id ?? ""); const [reason, setReason] = useState(topic?.description ?? "");
  function save() { if (!target || !reason.trim()) return; onSave(target, reason); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Escalate to Next Tier</DialogTitle><DialogDescription>{topic?.title} will appear on the selected higher-tier board.</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Next Tier Board"><Select value={target} onValueChange={(value) => setTarget(value ?? "")}><SelectTrigger className="w-full"><SelectValue placeholder="Select target board" /></SelectTrigger><SelectContent>{targets.map((board) => <SelectItem key={board.id} value={board.id}>{board.name} · {board.tier}</SelectItem>)}</SelectContent></Select></Field><Field label="Reason"><Textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={4} /></Field></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={!target || !reason.trim()} onClick={save}><AlertTriangle className="size-4" />Escalate</Button></DialogFooter></DialogContent></Dialog>;
}

function CompleteDialog({ open, onOpenChange, meeting, topics, redCount, onComplete }: { open: boolean; onOpenChange: (open: boolean) => void; meeting: VisualManagementMeeting; topics: number; redCount: number; onComplete: () => void }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Complete Meeting?</DialogTitle><DialogDescription>Review the meeting summary. The completed meeting will be stored in history and remain printable.</DialogDescription></DialogHeader><div className="grid grid-cols-2 gap-3 rounded-lg border bg-muted/25 p-4 text-sm"><Meta label="Duration" value={`${meetingDurationMinutes(meeting)} min`} /><Meta label="Participants" value={String(meeting.participants.filter((person) => person.attendance === "Present").length)} /><Meta label="Red KPI Areas" value={String(redCount)} /><Meta label="Topics" value={String(topics)} /><Meta label="Actions" value={String(meeting.actionIds.length)} /><Meta label="Escalations" value={String(meeting.escalationIds.length)} /><Meta label="Decisions" value={String(meeting.decisionIds.length)} /><Meta label="Red Flags / CI" value={`${meeting.redFlagIds.length} / ${meeting.continuousImprovementIds.length}`} /></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Continue Meeting</Button><Button onClick={onComplete}><Check className="size-4" />Complete Meeting</Button></DialogFooter></DialogContent></Dialog>; }
