import { NextRequest, NextResponse } from "next/server";
import { applyConfirmedKpiAnswers, normalizeKpiAnalysisForContext, parseDriverSuggestions, parseKpiAnalysis, type KpiConfirmedAnswers, type KpiLevel } from "@/features/visual-management/kpi-configuration";
import { GROQ_API_BASE, GROQ_EXTRACTION_MODEL, describeGroqFailure, getGroqApiKey } from "@/lib/voice-capture/groq";

export const runtime = "nodejs";
const LOG_CONTEXT = "visual-management/kpi/analyze";
const SYSTEM = `You assist manufacturing teams in configuring recognized operational KPIs. Return strict JSON only. Never include hidden reasoning. Infer semantic configuration, but never invent organization-specific facts. Baseline, target, target date, measurement context, owner, actual performance, and Amber/Red boundaries must come only from the objective or confirmed follow-up answers. Never select or suggest an owner. Unknown facts must be null and listed as missing. Never copy numeric values or dates from examples into an answer. Prefer established manufacturing terminology, including First Pass Yield, Internal Defect Rate, Final Inspection Pass Rate, Corrective Action Closure Rate, OEE, PM Compliance, and Process Compliance. A Functional KPI used as an upstream controllable driver of a parent Unit KPI should normally be leading. A yield or pass-rate KPI is normally percentage and higher_is_better; a defect or complaint-rate KPI is normally number or percentage and lower_is_better. These names are contextual examples only. Canonical buckets: safety, quality, cost, delivery, people, environment. Indicator types: leading, lagging. Measurement types: count, percentage, number. Directions: higher_is_better, lower_is_better, target_exactly. Review frequencies: daily, weekly, monthly. SMART statuses: complete, missing_information, needs_context. Driver descriptions and relationship explanations must use cautious language such as "can contribute to", "can help", or "may support". Never use "directly reduces", "will reduce", "ensures", "guarantees", or "prevents" for causal relationships.`;

export async function POST(request: NextRequest) {
  const apiKey = getGroqApiKey();
  if (!apiKey) return NextResponse.json({ error: "AI analysis is temporarily unavailable." }, { status: 503 });
  let body: Record<string, unknown>;
  try { body = await request.json() as Record<string, unknown>; } catch { return NextResponse.json({ error: "Invalid request." }, { status: 400 }); }
  const mode = body.mode === "drivers" ? "drivers" : "analyze";
  const objective = typeof body.objective === "string" ? body.objective.trim() : "";
  if (mode === "analyze" && (!objective || objective.length > 4000)) return NextResponse.json({ error: "Enter a valid objective." }, { status: 400 });
  const contract = mode === "drivers"
    ? `Suggest 3-5 recognized manufacturing Functional KPI drivers for the parent Unit KPI and selected function. Do not select one. Use conventional KPI names and briefly explain how each may support or can contribute to the parent outcome without claiming guaranteed causality. For a Quality function contributing to Customer Complaint Rate, appropriate contextual candidates can include First Pass Yield, Internal Defect Rate, Final Inspection Pass Rate, or Corrective Action Closure Rate; do not limit other contexts to these examples. Shape: {"suggestions":[{"name":string,"description":string}]}. Context: ${JSON.stringify(body.context ?? {})}`
    : `Analyze the objective using SMART and apply standard manufacturing KPI terminology. Extract factual values only when literally supplied by the objective or confirmed answers. Preserve every confirmed answer exactly. Shape: {"smart":{"specific":{"status":enum,"explanation":string},"measurable":...,"achievable":...,"relevant":...,"timely":...},"complete":boolean,"suggestedKpiName":string,"suggestedBucket":enum,"suggestedIndicatorType":enum,"suggestedMeasurementType":enum,"suggestedDirection":enum,"suggestedReviewFrequency":"daily"|"weekly"|"monthly" optional,"extractedFacts":{"baseline":number|null,"target":number|null,"targetDate":"YYYY-MM-DD"|null,"measurementContext":string|null},"missingFacts":["baseline"|"target"|"targetDate"|"measurementContext"],"followUpQuestions":[{"id":string,"factKey":"baseline"|"target"|"targetDate"|"measurementContext","label":string,"helperText":string optional,"inputType":"number"|"text"|"date","unitHint":string optional,"required":boolean}],"draftSmartObjective":string,"relationshipExplanation":string optional}. Ask only relevant missing questions. Measurement context is missing only when the KPI cannot be understood safely without a denominator or definition. Mark complete only when baseline, target, and target date are user-derived; owner and threshold are handled separately. Objective: ${objective}\nContext and confirmed answers: ${JSON.stringify(body.context ?? {})}`;
  try {
    const upstream = await fetch(`${GROQ_API_BASE}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: GROQ_EXTRACTION_MODEL, temperature: 0.2, response_format: { type: "json_object" }, messages: [{ role: "system", content: SYSTEM }, { role: "user", content: contract }] }) });
    if (!upstream.ok) { const detail = await upstream.text().catch(() => ""); const failure = describeGroqFailure(upstream.status, detail, LOG_CONTEXT); return NextResponse.json({ error: "AI analysis is temporarily unavailable." }, { status: failure.status }); }
    const payload = await upstream.json() as { choices?: Array<{ message?: { content?: string } }> }; const raw = payload.choices?.[0]?.message?.content;
    if (!raw) return NextResponse.json({ error: "AI analysis is temporarily unavailable." }, { status: 502 });
    let parsed: unknown; try { parsed = JSON.parse(raw); } catch { return NextResponse.json({ error: "AI analysis is temporarily unavailable." }, { status: 502 }); }
    const validated = mode === "drivers" ? parseDriverSuggestions(parsed) : parseKpiAnalysis(parsed);
    if (!validated) return NextResponse.json({ error: "AI analysis is temporarily unavailable." }, { status: 502 });
    if (mode === "drivers") return NextResponse.json({ suggestions: validated });
    const analysis = validated as NonNullable<ReturnType<typeof parseKpiAnalysis>>;
    const context = body.context && typeof body.context === "object" ? body.context as Record<string, unknown> : {};
    const answers = context.answers && typeof context.answers === "object" ? context.answers as KpiConfirmedAnswers : {};
    const parent = context.parent && typeof context.parent === "object" ? context.parent as Record<string, unknown> : {};
    const normalized = normalizeKpiAnalysisForContext(analysis, { level: context.level === "functional" ? "functional" : "unit" as KpiLevel, driver: typeof context.driver === "string" ? context.driver : undefined, parentName: typeof parent.name === "string" ? parent.name : undefined, functionName: typeof context.functionName === "string" ? context.functionName : undefined });
    return NextResponse.json(applyConfirmedKpiAnswers(normalized, answers));
  } catch (error) { console.error(`[${LOG_CONTEXT}] request failed`, error); return NextResponse.json({ error: "AI analysis is temporarily unavailable." }, { status: 502 }); }
}
