"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, ClipboardCheck, Copy, Eye, FileText, Image as ImageIcon, Printer, Search, Share2, Sparkles } from "lucide-react";

import { PageContainer } from "@/components/layout/page-container";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useActionStore } from "@/lib/actions/action-store";
import { FIVE_S_ZONE_CONFIGURATION } from "@/lib/five-s/configuration";
import { useFiveSAuditStore } from "@/lib/five-s/audit-store";
import FiveSPageHeader from "./components/FiveSPageHeader";
import { ActionFlowChart, CostSavingTrend, ReportAuditTrend } from "./reports-analytics";
import type { FiveSAudit } from "./types/five-s";
import type { MyAction, MyActionEvidence } from "./types/my-actions";
import { useI18n } from "@/components/preferences/use-i18n";
import { canSeeImprovement, useImprovements } from "./continuous-improvement/store";
import type { ContinuousImprovement } from "./continuous-improvement/types";
import { useCurrentUser } from "@/lib/current-user";
import { buildFiveSReportData } from "./reports-data";

type Tab = "overview" | "audits" | "actions" | "improvements";
type LibraryItem = { type: "audit"; audit: FiveSAudit; score: number; date: string } | { type: "action"; action: MyAction; date: string };
const TABS: Array<{ value: Tab; label: string }> = [{value:"overview",label:"Overview"},{value:"audits",label:"Audit Reports"},{value:"actions",label:"Action Reports"},{value:"improvements",label:"Improvements"}];

function pct(audit: FiveSAudit) { return audit.maxScore ? Math.round((audit.score / audit.maxScore) * 100) : 0; }
function date(value?: string) { if (!value) return "—"; const parsed = new Date(value.includes("T")?value:`${value}T00:00:00`); return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(parsed); }
export default function FiveSReportsPage({ initialTab, initialSearch = "", initialSort = "Newest" }: { initialTab?: string; initialSearch?: string; initialSort?: string }) {
  const router = useRouter(); const audits = useFiveSAuditStore(); const actions = useActionStore(); const improvements = useImprovements(); const currentUser = useCurrentUser();
  const { t } = useI18n();
  const initialReportTab: Tab = TABS.some((item)=>item.value===initialTab) ? initialTab as Tab : "overview";
  const [tab,setTab]=useState<Tab>(initialReportTab); const [search,setSearch]=useState(initialSearch); const [type,setType]=useState("All"); const [zone,setZone]=useState("All"); const [sort,setSort]=useState(initialSort); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [copied,setCopied]=useState<string>();
  const allCompletedAudits = audits.filter((audit)=>audit.status==="Completed"); const allCompletedActions = actions.filter((action)=>action.status==="Completed");
  const completedImprovements = improvements.filter((improvement)=>improvement.status==="completed"&&canSeeImprovement(improvement,currentUser));

  const intelligence = useMemo(()=>buildFiveSReportData(audits,actions,{from,to}),[actions,audits,from,to]);

  const library=useMemo(()=>{
    let items:LibraryItem[]=[...allCompletedAudits.map((audit):LibraryItem=>({type:"audit",audit,score:pct(audit),date:audit.completedAt??audit.startedAt??audit.dueDate})),...allCompletedActions.map((action):LibraryItem=>({type:"action",action,date:action.completedAt??action.createdAt}))];
    const targetType=tab==="audits"?"Audit":tab==="actions"?"Action":type; if(targetType!=="All")items=items.filter((item)=>item.type===targetType.toLowerCase());
    items=items.filter((item)=>{const z=item.type==="audit"?item.audit.area:item.action.area;const hay=item.type==="audit"?`${item.audit.id} ${item.audit.title} ${item.audit.plant} ${item.audit.area} ${item.audit.auditor}`:`${item.action.id} ${item.action.title} ${item.action.area} ${item.action.responsiblePersonName??item.action.assignedTo}`;return(tab!=="overview"||zone==="All"||z===zone)&&(!search||hay.toLowerCase().includes(search.toLowerCase()))&&(!from||item.date.slice(0,10)>=from)&&(!to||item.date.slice(0,10)<=to);});
    return items.sort((a,b)=>{if(sort==="Oldest")return a.date.localeCompare(b.date);if(sort==="Highest Score"||sort==="Highest Audit Score")return (b.type==="audit"?b.score:-1)-(a.type==="audit"?a.score:-1);if(sort==="Lowest Score")return (a.type==="audit"?a.score:101)-(b.type==="audit"?b.score:101);if(sort==="Highest Cost Saving")return (b.type==="action"?(b.action.costSaving??0):-1)-(a.type==="action"?(a.action.costSaving??0):-1);if(sort==="Lowest Cost Saving")return (a.type==="action"?(a.action.costSaving??0):Number.MAX_VALUE)-(b.type==="action"?(b.action.costSaving??0):Number.MAX_VALUE);if(sort==="Zone")return (a.type==="audit"?a.audit.area:a.action.area).localeCompare(b.type==="audit"?b.audit.area:b.action.area);return b.date.localeCompare(a.date);});
  },[allCompletedActions,allCompletedAudits,from,search,sort,tab,to,type,zone]);

  const improvementReports=useMemo(()=>completedImprovements.filter((item)=>!search||`${item.id} ${item.title} ${item.zone} ${item.proposedByName} ${item.completedByName??""}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>{const aDate=a.completedAt??a.createdAt,bDate=b.completedAt??b.createdAt;if(sort==="Oldest")return aDate.localeCompare(bDate);if(sort==="Highest Actual Saving")return (b.actualSaving??0)-(a.actualSaving??0);if(sort==="Highest Proposed Saving")return b.proposedSaving-a.proposedSaving;return bDate.localeCompare(aDate);}),[completedImprovements,search,sort]);

  useEffect(()=>{const params=new URLSearchParams();params.set("tab",tab);if(search)params.set("q",search);if(sort!=="Newest")params.set("sort",sort);router.replace(`/5s/reports?${params.toString()}`,{scroll:false});},[router,search,sort,tab]);
  function changeTab(next:Tab){setTab(next);setSearch("");setSort("Newest");}
  function open(item:LibraryItem){const returnTo=`/5s/reports?tab=${item.type==="audit"?"audits":"actions"}${search?`&q=${encodeURIComponent(search)}`:""}${sort!=="Newest"?`&sort=${encodeURIComponent(sort)}`:""}`;const context=`?from=${item.type==="audit"?"reports-audit":"reports-action"}&returnTo=${encodeURIComponent(returnTo)}`;router.push(item.type==="audit"?`/5s/audits/${encodeURIComponent(item.audit.id)}/report${context}`:`/5s/actions/${encodeURIComponent(item.action.id)}/report${context}`);}
  async function share(item:LibraryItem){const path=item.type==="audit"?`/5s/audits/${item.audit.id}/report`:`/5s/actions/${item.action.id}/report`;const url=`${window.location.origin}${path}`;if(navigator.share){try{await navigator.share({title:"5S Report",url});return;}catch{}}await navigator.clipboard.writeText(url);setCopied(path);setTimeout(()=>setCopied(undefined),1800);}
  async function shareImprovement(item:ContinuousImprovement){const path=`/5s/continuous-improvement/${item.id}/report`;const url=`${window.location.origin}${path}`;if(navigator.share){try{await navigator.share({title:`Continuous Improvement Report · ${item.id}`,url});return;}catch{}}await navigator.clipboard.writeText(url);setCopied(path);setTimeout(()=>setCopied(undefined),1800);}

  const dedicatedReportTab = tab === "audits" || tab === "actions" || tab === "improvements";
  const dedicatedSortOptions = tab === "audits" ? ["Newest","Oldest","Highest Score","Lowest Score"] : tab === "improvements" ? ["Newest","Oldest","Highest Actual Saving","Highest Proposed Saving"] : ["Newest","Oldest","Highest Cost Saving","Lowest Cost Saving"];

  return <PageContainer className="max-w-none"><FiveSPageHeader eyebrow="5S Workspace" title="Reports" description="Review performance, improvements and generated audit records across your plant." actions={dedicatedReportTab ? <div className="flex w-full min-w-0 flex-wrap gap-2 sm:w-auto"><div className="relative min-w-0 flex-1 sm:w-[300px] sm:flex-none"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={(e)=>setSearch(e.target.value)} className="pl-9" placeholder={tab==="audits"?"Search audit reports...":tab==="improvements"?"Search improvement reports...":"Search action reports..."}/></div><div className="min-w-36 flex-1 sm:w-44 sm:flex-none"><Filter value={sort} onChange={setSort} label="Newest" options={dedicatedSortOptions} hideAll/></div></div> : tab === "overview" ? <div className="grid w-full grid-cols-2 gap-2 sm:w-auto"><Input aria-label="From date" type="date" value={from} onChange={(e)=>setFrom(e.target.value)} className="min-w-0"/><Input aria-label="To date" type="date" min={from||undefined} value={to} onChange={(e)=>setTo(e.target.value)} className="min-w-0"/></div> : undefined} />
    <nav className="flex gap-1 overflow-x-auto rounded-lg border bg-muted/20 p-1" aria-label="Report sections">{TABS.map((item)=><Button key={item.value} size="sm" variant={tab===item.value?"default":"ghost"} onClick={()=>changeTab(item.value)} className="whitespace-nowrap">{item.value === "overview" ? t("reports.overview") : item.value === "audits" ? t("reports.auditReports") : item.value === "actions" ? t("reports.actionReports") : t("reports.improvements")}</Button>)}</nav>

    {tab==="improvements"&&<section className="grid gap-4"><div><h2 className="text-lg font-semibold">Continuous Improvement Reports</h2><p className="mt-1 text-sm text-muted-foreground">Completed employee-led improvements with before-and-after evidence and measured savings.</p></div>{improvementReports.length?<div className="grid gap-4 xl:grid-cols-2">{improvementReports.map(item=><ContinuousImprovementReportCard key={item.id} item={item} copied={copied===`/5s/continuous-improvement/${item.id}/report`} onOpen={()=>router.push(`/5s/continuous-improvement/${item.id}/report`)} onShare={()=>shareImprovement(item)}/>)}</div>:<div className="grid min-h-52 place-items-center rounded-xl border border-dashed bg-card text-center"><div><Sparkles className="mx-auto size-8 text-muted-foreground"/><p className="mt-3 font-medium">No completed improvement reports yet</p><p className="mt-1 text-sm text-muted-foreground">Completed Continuous Improvements will automatically appear here.</p></div></div>}</section>}

    {tab==="overview"&&<><ExecutiveSummary score={intelligence.score} audits={intelligence.completedAudits.length} actions={intelligence.correctiveActions.length} closed={intelligence.completedCorrectiveActions.length} saving={intelligence.totalSaving} change={intelligence.trendChange}/>
      <div className="grid min-w-0 gap-5 xl:grid-cols-2"><ReportAuditTrend data={intelligence.auditTrend}/><ZoneRanking data={intelligence.zoneRanking}/><ActionFlowChart data={intelligence.statusFlow}/><CostSavingTrend data={intelligence.savingTrend}/></div>
      <div className="grid min-w-0 gap-5 xl:grid-cols-[1.35fr_.65fr]"><StoryGraph audit={intelligence.featuredAudit} actions={intelligence.storyActions} saving={intelligence.storySaving}/><ClosurePanel rate={intelligence.closureRate} days={intelligence.avgDays} overdue={intelligence.overdue} rework={intelligence.rework}/></div>
      <ImprovementHighlights actions={intelligence.completedCorrectiveActions.slice(0,4)} onOpen={(action)=>router.push(`/5s/actions/${action.id}/report`)}/>
    </>}

    {tab!=="improvements"&&<section className="grid gap-4"><div><h2 className="text-lg font-semibold">{tab==="audits"?"Audit Reports":tab==="actions"?"Action Reports":"Report Library"}</h2><p className="mt-1 text-sm text-muted-foreground">{tab==="overview"?"All generated audit and improvement reports in one place.":"Browse completed reports and open the original report viewer."}</p></div>{tab==="overview"&&<div className="grid gap-2 rounded-xl border bg-card p-3 md:grid-cols-3 xl:grid-cols-[minmax(240px,1.5fr)_repeat(3,minmax(140px,.7fr))]"> <div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={(e)=>setSearch(e.target.value)} className="pl-9" placeholder="Search report ID, audit or action..."/></div><Filter value={type} onChange={setType} label="All report types" options={["Audit","Action"]}/><Filter value={zone} onChange={setZone} label="All Zones" options={FIVE_S_ZONE_CONFIGURATION.map((z)=>z.name)}/><Filter value={sort} onChange={setSort} label="Newest" options={["Newest","Oldest","Highest Audit Score","Highest Cost Saving","Zone"]} hideAll/></div>}
      {library.length?<div className="grid gap-3 lg:grid-cols-2">{library.map((item)=><ReportCard key={item.type==="audit"?item.audit.id:item.action.id} item={item} onOpen={()=>open(item)} onShare={()=>share(item)} copied={Boolean(copied)}/>)}</div>:<div className="grid min-h-44 place-items-center rounded-xl border border-dashed bg-card text-center"><div><FileText className="mx-auto size-7 text-muted-foreground"/><p className="mt-3 font-medium">No completed reports yet</p><p className="mt-1 text-sm text-muted-foreground">Completed Audits and Actions automatically appear here.</p></div></div>}
    </section>}
  </PageContainer>;
}

function ExecutiveSummary({score,audits,actions,closed,saving,change}:{score:number|null;audits:number;actions:number;closed:number;saving:number;change:number}){return <section className="relative overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[1.1fr_2fr] lg:items-center"><div className="border-b pb-5 lg:border-b-0 lg:border-r lg:pb-0 lg:pr-8"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-primary">Reporting Period · Current Selection</p><div className="mt-4 flex items-end gap-4"><span className="text-5xl font-semibold tracking-[-.05em]">{score===null?"—":`${score}%`}</span><div className="pb-1"><p className="text-sm font-semibold">Overall 5S Performance</p><p className={`mt-1 text-xs ${change>=0?"text-emerald-600":"text-red-600"}`}>{score===null?"No completed audits in period":`${change>=0?"↑":"↓"} ${Math.abs(change)}% vs previous period`}</p></div></div></div><div className="grid grid-cols-2 gap-5 sm:grid-cols-4"><HeroMetric value={audits} label="Audits Completed"/><HeroMetric value={actions} label="Corrective Actions"/><HeroMetric value={closed} label="Actions Closed"/><HeroMetric value={`₹${saving.toLocaleString("en-IN")}`} label="Recorded Saving"/></div></div></section>}
function HeroMetric({value,label}:{value:string|number;label:string}){return <div><p className="text-xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>}
function ZoneRanking({data}:{data:Array<{zone:string;leader:string;score:number}>}){return <Card><CardHeader className="border-b"><CardTitle className="text-base">Zone Performance Ranking</CardTitle><p className="text-xs text-muted-foreground">Compliance performance and accountable leaders.</p></CardHeader><CardContent className="grid gap-4 pt-5">{data.map((item,index)=><div key={item.zone} className="grid grid-cols-[28px_1fr_auto] items-center gap-3"><span className="grid size-7 place-items-center rounded-md bg-muted text-xs font-semibold">{index+1}</span><div><div className="flex justify-between text-sm"><span className="font-semibold">{item.zone}</span><span className="font-semibold">{item.score}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${item.score}%`}}/></div><p className="mt-1 text-[11px] text-muted-foreground">{item.leader}</p></div><Badge variant={item.score>=80?"success":item.score>=60?"warning":"danger"}>{item.score>=80?"Good":item.score>=60?"Attention":"Critical"}</Badge></div>)}</CardContent></Card>}
function StoryGraph({audit,actions,saving}:{audit?:FiveSAudit;actions:MyAction[];saving:number}){const steps=[{label:"Audit",value:audit?.id??"—"},{label:"Compliance",value:audit?`${pct(audit)}%`:"—"},{label:"Actions",value:actions.length},{label:"Closed",value:actions.filter((a)=>a.status==="Completed").length},{label:"Saving",value:`₹${saving.toLocaleString("en-IN")}`}];return <Card className="min-w-0"><CardHeader className="min-w-0 border-b"><CardTitle className="break-words text-base">Audit → Action → Improvement</CardTitle><p className="break-words text-xs text-muted-foreground">The operational story from finding to measurable outcome.</p></CardHeader><CardContent className="min-w-0 overflow-x-auto py-7"><div className="flex min-w-[650px] items-center justify-between">{steps.map((step,index)=><div key={step.label} className="contents"><div className="min-w-24 text-center"><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{step.label}</p><p className="mt-2 text-base font-semibold">{step.value}</p></div>{index<steps.length-1&&<ArrowRight className="size-4 text-primary"/>}</div>)}</div></CardContent></Card>}
function ClosurePanel({rate,days,overdue,rework}:{rate:number;days:string;overdue:number;rework:number}){return <Card className="min-w-0"><CardHeader className="min-w-0 border-b"><CardTitle className="break-words text-base">Closure Performance</CardTitle><p className="break-words text-xs text-muted-foreground">Management view of corrective-action effectiveness.</p></CardHeader><CardContent className="grid min-w-0 grid-cols-2 gap-px bg-border p-0"><Mini value={`${rate}%`} label="Closure Rate"/><Mini value={days==="—"?days:`${days} days`} label="Avg. Closure Time"/><Mini value={overdue} label="Overdue" attention/><Mini value={`${rework}%`} label="Rework Rate"/></CardContent></Card>}
function Mini({value,label,attention}:{value:string|number;label:string;attention?:boolean}){return <div className="bg-card p-4"><p className={`text-xl font-semibold ${attention&&Number(value)>0?"text-red-600":""}`}>{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>}
function ImprovementHighlights({actions,onOpen}:{actions:MyAction[];onOpen:(a:MyAction)=>void}){return <section><div className="mb-3"><h2 className="text-lg font-semibold">Improvement Highlights</h2><p className="mt-1 text-sm text-muted-foreground">Visual proof of completed workplace improvements.</p></div>{actions.length?<div className="grid gap-4 xl:grid-cols-2">{actions.map((a)=><Improvement key={a.id} action={a} onOpen={()=>onOpen(a)}/>)}</div>:<div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No completed improvements yet.</div>}</section>}
function Improvement({action,onOpen}:{action:MyAction;onOpen:()=>void}){const before=action.issueEvidence?.find((e)=>e.type==="image"&&e.url);const after=action.evidence.find((e)=>e.type==="image"&&e.url);return <Card className="min-w-0 overflow-hidden"><div className="flex min-w-0 flex-wrap items-start justify-between gap-3 border-b px-4 py-3"><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold uppercase tracking-wider text-primary">{action.area} · {action.category}</p><h3 className="mt-1 line-clamp-2 break-words font-semibold">{action.title}</h3></div><Badge variant="success">Completed</Badge></div><div className="grid gap-3 p-4 sm:grid-cols-[1fr_30px_1fr] sm:items-center"><Evidence label="Before" item={before}/><ArrowRight className="mx-auto hidden size-4 text-primary sm:block"/><Evidence label="After" item={after}/></div><div className="flex min-w-0 flex-wrap items-center justify-between gap-2 border-t bg-muted/10 px-4 py-3 text-xs"><span className="min-w-0 break-words"><b>{action.completedByName??action.responsiblePersonName??action.assignedTo}</b> · Completed By</span><span className="font-semibold text-emerald-700">₹{(action.costSaving??0).toLocaleString("en-IN")} saving</span><Button size="sm" variant="ghost" onClick={onOpen}>View Improvement Report <ArrowRight className="size-3.5"/></Button></div></Card>}
function ContinuousImprovementReportCard({item,onOpen,onShare,copied}:{item:ContinuousImprovement;onOpen:()=>void;onShare:()=>void;copied:boolean}){const before=item.existingPhotos?.[0],after=item.evidence[0];return <Card className="min-w-0 overflow-hidden"><div className="flex min-w-0 items-start gap-3 border-b p-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><Sparkles className="size-5"/></span><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-primary">Continuous Improvement Report</p><h3 className="mt-1 font-mono text-sm font-semibold">{item.id}</h3><p className="mt-1 line-clamp-2 text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.zone} · Proposed by {item.proposedByName} · {date(item.completedAt)}</p></div><Badge variant="success" className="shrink-0">Completed</Badge></div><div className="grid gap-3 p-4 sm:grid-cols-[1fr_30px_1fr] sm:items-center"><ImprovementReportEvidence label="Before" name={before?.name} url={before?.url}/><ArrowRight className="mx-auto hidden size-4 text-primary sm:block"/><ImprovementReportEvidence label="After" name={after?.name} url={after?.url}/></div><div className="grid gap-3 border-t bg-muted/10 px-4 py-3 text-xs sm:grid-cols-3"><div><span className="text-muted-foreground">Completed by</span><p className="mt-0.5 font-semibold">{item.completedByName??item.memberNames[0]??item.proposedByName}</p></div><div><span className="text-muted-foreground">Proposed saving</span><p className="mt-0.5 font-semibold">₹{item.proposedSaving.toLocaleString("en-IN")}</p></div><div><span className="text-muted-foreground">Actual saving</span><p className="mt-0.5 font-semibold text-emerald-700 dark:text-emerald-400">₹{(item.actualSaving??0).toLocaleString("en-IN")}</p></div></div><div className="grid grid-cols-3 gap-1 border-t px-3 py-2"><Button size="sm" variant="ghost" onClick={onOpen}><Eye className="size-4"/>Preview</Button><Button size="sm" variant="ghost" onClick={onShare}>{copied?<Copy className="size-4"/>:<Share2 className="size-4"/>}{copied?"Copied":"Share"}</Button><Button size="sm" variant="ghost" onClick={onOpen}><Printer className="size-4"/>Print</Button></div></Card>}
function ImprovementReportEvidence({label,name,url}:{label:string;name?:string;url?:string}){return <div><div className="mb-1.5 flex items-center justify-between gap-2"><p className={`text-[10px] font-bold uppercase tracking-wider ${label==="Before"?"text-red-600 dark:text-red-400":"text-emerald-700 dark:text-emerald-400"}`}>{label}</p>{name&&<span className="max-w-[70%] truncate text-[10px] text-muted-foreground" title={name}>{name}</span>}</div><div className="aspect-[16/9] overflow-hidden rounded-lg border bg-muted">{url?<img src={url} alt={`${label} evidence: ${name??"Continuous Improvement"}`} className="size-full object-cover"/>:<div className="grid size-full place-items-center"><ImageIcon className="size-5 text-muted-foreground"/></div>}</div></div>}
function Evidence({label,item}:{label:string;item?:MyActionEvidence}){return <div><p className={`mb-1 text-[10px] font-bold uppercase tracking-wider ${label==="Before"?"text-red-600":"text-green-600"}`}>{label}</p><div className="aspect-[16/9] overflow-hidden rounded-lg border bg-muted">{item?.url?<img src={item.url} alt={item.name} className="size-full object-cover"/>:<div className="grid size-full place-items-center"><ImageIcon className="size-5 text-muted-foreground"/></div>}</div></div>}
function Filter({value,onChange,label,options,hideAll}:{value:string;onChange:(v:string)=>void;label:string;options:string[];hideAll?:boolean}){return <Select value={value} onValueChange={(v)=>onChange(v??(hideAll?label:"All"))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{!hideAll&&<SelectItem value="All">{label}</SelectItem>}{options.map((option)=><SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select>}
function ReportCard({item,onOpen,onShare,copied}:{item:LibraryItem;onOpen:()=>void;onShare:()=>void;copied:boolean}){const audit=item.type==="audit"?item.audit:null;const action=item.type==="action"?item.action:null;return <Card className="min-w-0 overflow-hidden"><div className="flex min-w-0 flex-wrap gap-3 p-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary">{audit?<ClipboardCheck className="size-5"/>:<Sparkles className="size-5"/>}</span><div className="min-w-0 flex-1"><p className="break-words text-[10px] font-semibold uppercase tracking-[.12em] text-primary">{audit?"5S Audit Report":"5S Improvement Report"}</p><h3 className="mt-1 break-all font-semibold">{audit?audit.id:action!.id}</h3><p className="mt-1 line-clamp-2 break-words text-sm text-muted-foreground">{audit?`${audit.area} · ${audit.plant}`:action!.title}</p><div className="mt-3 flex min-w-0 flex-wrap gap-x-5 gap-y-1 text-xs"><span className="min-w-0 break-words"><b>{audit?`${item.type==="audit"?item.score:0}%`:action!.responsiblePersonName??action!.assignedTo}</b> {audit?"Score":"Completed by"}</span><span className="break-words">{audit?audit.auditor:`₹${(action!.costSaving??0).toLocaleString("en-IN")} saving`}</span><span>{date(item.date)}</span></div></div><Badge variant="success" className="self-start">Completed</Badge></div><div className="grid grid-cols-1 gap-1 border-t bg-muted/10 px-3 py-2 min-[360px]:grid-cols-3"><Button size="sm" variant="ghost" className="w-full" onClick={onOpen}><Eye className="size-4"/> Preview</Button><Button size="sm" variant="ghost" className="w-full" onClick={onShare}>{copied?<Copy className="size-4"/>:<Share2 className="size-4"/>} {copied?"Copied":"Share"}</Button><Button size="sm" variant="ghost" className="w-full" onClick={onOpen}><Printer className="size-4"/> Print</Button></div></Card>}
